# HyDE (Hypothetical Document Embedding) 실험

HyDE(Hypothetical Document Embeddings)는 **사용자 질문에 대해 LLM(대형 언어 모델)로 가상의 문서를 먼저 생성하고, 이 문서를 임베딩하여 검색하는 방식**이다.  
기존에는 질문 자체를 임베딩해 유사한 문서를 찾았지만, HyDE는 질문의 맥락과 의도를 더 잘 반영할 수 있는 가상 문서를 생성해 임베딩하고, 이를 벡터 DB에서 비교함으로써 **더 정확한 검색 결과**를 얻을 수 있다.

**핵심 요약**
- 질문 → LLM이 가상 문서 생성 → 임베딩 → 벡터 DB에서 유사도 검색
- 기존 방식보다 **질문의 의미와 맥락을 더 잘 반영**하여 검색 정확도 향상
- RAG 등 다양한 검색·생성 AI 시스템에서 활용 가능
- 단점: LLM 사용으로 **속도가 느려질 수 있음**

In [1]:
from dotenv import load_dotenv
import os

load_dotenv()
os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
os.environ['PINECONE_API_KEY'] = os.getenv('PINECONE_API_KEY')
os.environ['LANGSMITH_TRACING'] = 'true'
os.environ['LANGSMITH_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGSMITH_PROJECT'] = 'skn34-langchain'
os.environ['LANGSMITH_API_KEY'] = os.getenv('LANGSMITH_API_KEY')

In [11]:
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore

embeddings = OpenAIEmbeddings(model = 'text-embedding-3-small')

# 벡터스토어 연결
vector_store = PineconeVectorStore(
    index_name= 'ir',   # 연결할 index명
    embedding= embeddings   # 사용할 임베딩 함수 (연결할 인덱스 차원과 임베딩 차원이 같아야 함
)

In [2]:
import pandas as pd

document_df = pd.read_csv('documents.csv')
queries_df = pd.read_csv('queries.csv')

queries_df

,query_id,query_text,relevant_doc_ids
0,Q1,제주도 올레길 트레킹 코스 추천,D1=3;D4=1;D30=1
1,Q2,전주 비빔밥 vs 진주 비빔밥 재료 및 맛 차이,D2=3
2,Q3,걸스데이 대표 히트곡 목록 알려줘,D3=3
3,Q4,훈민정음 창제 배경과 세종대왕의 의의,D4=3
4,Q5,이순신 장군이 명량 해전에서 사용한 전술은 무엇인가?,D5=3
5,Q6,2024년 기후 변화 주요 지표와 한국의 탄소 중립 정책,D6=3;D14=2;D26=1
6,Q7,한국 AI 윤리 이슈와 관련 정책 사례는?,D7=3;D25=2
7,Q8,서울 지하철 환승 시 T-money 사용 방법,D8=3
8,Q9,판소리 춘향가 줄거리와 공연 특징,D9=3
9,Q10,한국 축구 대표팀 2002년 한일 월드컵 4강 진출 이유,D10=3
10,Q11,건강한 생활습관 중 스트레스 관리 방법,D11=3
11,Q12,서울 근교 당일치기 여행지로 가평과 양평 중 추천,D12=3;D1=1
12,Q13,비빔밥을 저칼로리 다이어트 식단으로 활용하는 방법,D13=3;D11=1
13,Q14,AI 기반 기후 예측 논문 사례와 연구 기관,D14=3;D26=2
14,Q15,가야금 연주법과 현대 국악 앙상블 활용 사례,D15=3
15,Q16,전통 혼례 절차 중 폐백·예단의 의미,D16=3
16,Q17,2023년 한국 영화 Top10 중 액션 장르 영화,D17=3;D10=1
17,Q18,윈도우즈에서 matplotlib 한글 출력 설정,D18=3
18,Q19,코드 악취를 식별하고 리팩토링하는 방법,D19=3;D20=1
19,Q20,JUnit5와 JUnit4 차이점 및 Eclipse 설정 방법,D20=3
20,Q21,Wheel of Fortune 게임에서 전략적 알파벳 선택 방법,D21=3
21,Q22,싱글톤 패턴 구현 시 멀티스레드 안전성 보장 방법,D22=3
22,Q23,Strategy 패턴을 이용한 결제 시스템 구현 예,D23=3
23,Q24,Command 패턴으로 Undo 기능 구현하기,D24=3
24,Q25,2025년 한국 AI 정책의 주요 내용과 인재 양성 전략,D25=3
25,Q26,딥러닝 기반 기상 예측 모델 비교(LSTM vs Transformer),D26=3;D14=2
26,Q27,ChromaDB와 Qdrant 중 벡터 검색 성능 비교,D27=3;D26=1
27,Q28,Contextual Compression 적용 후 검색 성능 평가 방법,D28=3;D6=1
28,Q29,Self-Query Retriever로 생성할 만한 가상 질의 예시,D29=3
29,Q30,세종대왕 훈민정음 배경을 바탕으로 AI 윤리 가이드라인 사례 찾기 (Multi-Hop),D4=3;D7=2;D25=1

In [3]:
# BM25 키워드 검색 모델
# - 문서를 토큰화해서 BM25 모델 생성
# - 검색어도 동일하게 토큰화하여 BM25 검색시 활용

from rank_bm25 import BM25Okapi
from kiwipiepy import Kiwi

kiwi = Kiwi()

def kiwi_tokenize(doc):
    return [token.form for token in kiwi.tokenize(doc)]

# 문서 내용 토큰화
tokenized_docs = [kiwi_tokenize(doc) for doc in document_df['content']]
bm25 = BM25Okapi(tokenized_docs)    # BM25 모델 생성 (토큰화된 문서)

# 질의문을 토큰화해서 BM25로 상위 문서 검색하는 함수
def bm25_search(query,top_k = 5):
    query_tokens = kiwi_tokenize(query)         # 검색어 토큰화
    scores = bm25.get_scores(query_tokens)      # 각 문서의 BM25 점수 계산

    # 점수 기준 내림차순 정렬한 인덱스
    ranked_idx = sorted(range(len(scores)), key=lambda i :scores[i],reverse=True)
    # 상위 top_k개의 doc_id 리스트
    retrieved_docs = [document_df['doc_id'].iloc[i] for i in ranked_idx[:top_k]]
    return retrieved_docs

bm25_search('제주도 관광 명소')

['D1', 'D2', 'D3', 'D4', 'D5']

Hyde 가상문서 (가설답변) 생성 체인 구성

In [16]:
from langchain.chat_models import init_chat_model
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

llm = init_chat_model('gpt-5.6-luna', temperature=0.3)
prompt = PromptTemplate.from_template('''
질문 : {query}

위 질문에 대해서 실제 문서가 아니어도 좋으니, 답변을 생성해주세요.
''')
output_parser = StrOutputParser()

hyde_chain = prompt|llm|output_parser
print(hyde_chain.invoke('제주도 관광 명소'))

제주도에는 자연경관, 문화유산, 해변, 오름 등 다양한 관광 명소가 있습니다.

### 제주도 대표 관광 명소

1. **한라산 국립공원**
   - 제주도의 상징인 한라산을 만날 수 있는 곳입니다.
   - 성판악·관음사 탐방로를 통해 정상 등반이 가능하며, 짧은 산책 코스도 있습니다.

2. **성산일출봉**
   - 유네스코 세계자연유산으로 지정된 대표 명소입니다.
   - 정상에 오르면 바다와 주변 마을을 한눈에 볼 수 있으며, 일출 명소로 유명합니다.

3. **우도**
   - 성산항에서 배를 타고 갈 수 있는 작은 섬입니다.
   - 서빈백사, 검멀레해변, 우도봉 등이 유명하며 자전거나 전기차로 둘러보기 좋습니다.

4. **협재해수욕장**
   - 맑고 푸른 바다와 하얀 모래사장이 아름다운 해변입니다.
   - 비양도를 바라보며 산책하거나 해수욕을 즐기기 좋습니다.

5. **함덕해수욕장**
   - 수심이 비교적 얕고 해변 주변에 카페와 산책로가 잘 조성되어 있습니다.
   - 제주 동부 여행에서 방문하기 좋은 해변입니다.

6. **만장굴**
   - 세계적으로 유명한 용암동굴 중 하나입니다.
   - 독특한 지질 구조와 용암석주를 관찰할 수 있습니다.

7. **주상절리대**
   - 서귀포 중문 지역에 위치한 해안 절벽입니다.
   - 파도에 의해 만들어진 육각형 모양의 주상절리가 장관을 이룹니다.

8. **천지연폭포**
   - 서귀포의 대표적인 폭포로, 주변 산책로가 잘 조성되어 있습니다.
   - 밤에는 조명이 켜져 야경 명소로도 알려져 있습니다.

9. **오설록 티 뮤지엄**
   - 제주 녹차 문화를 체험할 수 있는 곳입니다.
   - 넓은 녹차밭과 카페, 전시 공간이 있어 사진 촬영 장소로도 인기가 많습니다.

10. **카멜리아힐**
    - 계절별로 다양한 꽃과 나무를 감상할 수 있는 수목원입니다.
    - 특히 동백꽃이 피는 계절에 아름답습니다.

11. **동문시장**
    - 제주 특산물과 해산물, 흑돼지 간식, 귤 관련 상품 등을 판매하는 전통시장입니다.
    - 저녁 시간에는 야시장 분위기도 즐길 수 있습니다.

12. **제주민속촌**
    - 제주 전통 가옥과 생활 문화를 살펴볼 수 있는 체험형 관광지입니다.

### 여행 코스 예시

- **제주 동부 코스:** 성산일출봉 → 우도 → 섭지코지 → 함덕해수욕장
- **제주 서부 코스:** 협재해수욕장 → 오설록 티 뮤지엄 → 산방산 → 용머리해안
- **제주 서귀포 코스:** 주상절리대 → 천지연폭포 → 정방폭포 → 중문관광단지
- **자연 중심 코스:** 한라산 → 사려니숲길 → 비자림 → 만장굴

제주도는 지역 간 이동 시간이 꽤 걸리므로 하루에 여러 명소를 방문하기보다는 동부·서부·서귀포처럼 지역을 나누어 여행하는 것이 좋습니다.

In [17]:
import time 
from tqdm.auto import tqdm

hyde_pseudo = {}

for idx, row in tqdm(queries_df.iterrows()):
    qid = row['query_id']
    query_text = row['query_text']
    pseudo_answer = hyde_chain.invoke(query_text)   # 가상 답변 생성
    hyde_pseudo[qid] = pseudo_answer    # {qid : pseudo_answer,...}
    time.sleep(0.5)     # API 과호출 방지용 딜레이

hyde_pseudo

0it [00:00, ?it/s]

{'Q1': '제주 올레길은 코스마다 풍경과 난이도가 달라서 여행 일정과 체력에 맞춰 선택하는 것이 좋습니다. 처음 걷는다면 아래 코스를 추천합니다.\n\n## 1. 가장 무난한 해안 풍경: 올레길 6코스\n- **구간:** 쇠소깍~제주올레여행자센터\n- **거리:** 약 11km\n- **소요 시간:** 4~5시간\n- **난이도:** 쉬움\n- **주요 풍경:** 쇠소깍, 검은모래 해변, 정방폭포 주변, 서귀포 해안\n- **추천 이유:** 비교적 짧고 대중교통과 식당 이용이 편리합니다. 바다와 마을 풍경을 균형 있게 볼 수 있어 첫 올레길로 좋습니다.\n\n## 2. 제주다운 해안 절경: 올레길 7코스\n- **구간:** 외돌개~월평\n- **거리:** 약 17.7km\n- **소요 시간:** 5~6시간\n- **난이도:** 보통\n- **주요 풍경:** 외돌개, 황우지해안, 법환포구, 월평해안\n- **추천 이유:** 제주 올레길 중 가장 유명한 코스 중 하나입니다. 해안 절벽과 바다 풍경이 아름답고 사진 찍기 좋습니다.\n- **주의:** 전체 코스가 길게 느껴질 수 있어 체력이 부담되면 외돌개~법환포구 구간만 걸어도 좋습니다.\n\n## 3. 성산일출봉을 만나는 코스: 올레길 1코스\n- **구간:** 시흥초등학교~광치기해변\n- **거리:** 약 15km\n- **소요 시간:** 4~5시간\n- **난이도:** 보통\n- **주요 풍경:** 말미오름, 알오름, 성산일출봉, 섭지코지 인근 풍경\n- **추천 이유:** 오름과 바다를 한 번에 경험할 수 있습니다. 날씨가 맑으면 성산일출봉 주변 경관이 특히 아름답습니다.\n- **주의:** 오름 구간은 바람이 강하거나 미끄러울 수 있습니다.\n\n## 4. 바다와 송악산 풍경: 올레길 10코스\n- **구간:** 화순금모래해변~하모체육공원\n- **거리:** 약 15.6km\n- **소요 시간:** 5시간 안팎\n- **난이도:** 보통\n- **주요 풍경:** 산방산, 용머리해안 주변, 송악산, 모슬포 해안\n- **추천 이유:** 제주 서남부의 대표적인 풍경을 볼 수 있는 코스입니다. 산방산과 송악산을 배경으로 걷는 길이 인상적입니다.\n- **주의:** 용머리해안은 기상과 물때에 따라 입장이 제한될 수 있습니다.\n\n## 5. 짧고 여유로운 숲길: 올레길 14-1코스\n- **구간:** 저지예술정보화마을~무릉외갓집\n- **거리:** 약 9km\n- **소요 시간:** 3~4시간\n- **난이도:** 쉬움~보통\n- **주요 풍경:** 곶자왈, 숲길, 밭길, 제주 중산간 마을\n- **추천 이유:** 바닷길보다 조용한 숲길을 선호한다면 좋습니다. 관광객이 비교적 적고 제주 중산간의 분위기를 느낄 수 있습니다.\n- **주의:** 숲길에서는 휴대전화 신호가 약한 구간이 있을 수 있으므로 이정표를 잘 확인해야 합니다.\n\n## 6. 제주 원도심과 해안 산책: 올레길 18코스\n- **구간:** 제주원도심~조천 만세동산\n- **거리:** 약 19km\n- **소요 시간:** 6시간 이상\n- **난이도:** 보통\n- **주요 풍경:** 제주항, 사라봉, 별도봉, 해안 마을, 조천 해안\n- **추천 이유:** 자연뿐 아니라 제주 도심과 역사적인 장소도 함께 볼 수 있습니다.\n- **주의:** 거리가 긴 편이라 하루 일정을 넉넉히 잡는 것이 좋습니다.\n\n## 여행 일정별 추천\n\n### 반나절만 걸을 때\n- 올레길 6코스 일부\n- 올레길 7코스 외돌개~법환포구\n- 올레길 9코스 대평포구 주변\n\n### 하루 동안 대표 풍경을 보고 싶을 때\n- 올레길 7코스\n- 올레길 10코스\n- 올레길 1코스\n\n### 조용한 길을 선호할 때\n- 올레길 14-1코스\n- 올레길 13코스\n- 올레길 18코스 일부\n\n### 대중교통을 이용할 때\n서귀포 중심 숙소라면 **6코스와 7코스**가 편리하고, 성산·모슬포 쪽 숙소라면 각각 **1코스와 10코스**를 선택하기 좋습니다. 코스 시작점과 종점의 버스 운행 간격이 길 수 있으므로 출발 전 교통편을 확인하는 것이 좋습니다.\n\n## 준비물과 주의사항\n- 미끄럽지 않은 트레킹화 또는 운동화\n- 물과 간단한 간식\n- 모자, 자외선 차단제, 우비\n- 바람막이 재킷\n- 휴대전화 보조배터리\n- 공식 올레길 앱 또는 코스 안내 지도\n\n제주도는 날씨가 빠르게 바뀌고 바람이 강한 날이 많습니다. 특히 오름과 해안 절벽 구간은 비가 온 뒤 미끄러울 수 있으므로 출발 전 날씨와 코스 통제 여부를 확인하세요.\n\n**처음 걷는다면 개인적으로는 올레길 6코스**, 제주다운 절경을 가장 많이 보고 싶다면 **7코스**, 성산일출봉까지 함께 보고 싶다면 **1코스**를 추천합니다.',
 'Q2': '## 전주비빔밥 vs 진주비빔밥\n\n두 음식 모두 여러 가지 나물과 고기, 양념을 밥에 섞어 먹는 전통 비빔밥이지만, **전주비빔밥은 재료의 다양성과 고소하고 진한 양념 맛**, **진주비빔밥은 색감과 나물의 담백함, 육회의 풍미**가 상대적으로 두드러집니다. 다만 가게와 조리법에 따라 차이가 있을 수 있습니다.\n\n| 구분 | 전주비빔밥 | 진주비빔밥 |\n|---|---|---|\n| 대표 특징 | 다양한 나물과 육회, 황포묵을 올림 | 여러 색의 나물을 꽃처럼 담는 ‘칠보화반’ |\n| 주요 재료 | 콩나물, 시금치, 고사리, 도라지, 표고버섯, 애호박, 무나물, 육회, 황포묵, 달걀 등 | 숙주나물, 고사리, 도라지, 시금치, 무나물, 애호박, 육회 등 |\n| 밥 | 쌀밥 또는 쇠고기 육수·콩나물 등을 활용한 밥 | 비교적 담백한 밥에 여러 나물을 곁들이는 방식 |\n| 양념 | 고추장, 참기름, 깨, 마늘 등 | 고추장과 참기름을 사용하지만 재료 본연의 맛을 살리는 편 |\n| 곁들임 | 콩나물국이 자주 함께 나옴 | 선짓국이나 국물을 곁들이는 경우가 있음 |\n| 맛의 인상 | 고소하고 진하며 감칠맛이 풍부함 | 담백하고 깔끔하며 나물과 육회의 맛이 선명함 |\n\n### 1. 전주비빔밥의 재료와 맛\n\n전주비빔밥은 보통 다음과 같은 재료를 사용합니다.\n\n- 여러 가지 나물\n- 콩나물\n- 육회 또는 익힌 쇠고기\n- 황포묵\n- 달걀\n- 표고버섯\n- 고추장\n- 참기름과 깨\n\n전주비빔밥의 특징은 **재료의 종류가 많고 각각의 나물을 따로 정성스럽게 무친다**는 점입니다. 특히 콩나물과 황포묵이 들어가 아삭하거나 부드러운 식감이 함께 느껴집니다.\n\n맛은 대체로 **고소하고 진하며 감칠맛이 풍부한 편**입니다. 고추장과 참기름을 넣고 비비면 양념 맛이 전체적으로 잘 어우러지고, 육회나 쇠고기가 들어갈 경우 고기 특유의 풍미도 강하게 느껴집니다.\n\n### 2. 진주비빔밥의 재료와 맛\n\n진주비빔밥은 ‘**칠보화반**’이라고도 불립니다. 여러 가지 나물을 일곱 가지 색처럼 아름답게 배치해 담아내는 것이 특징입니다.\n\n주로 들어가는 재료는 다음과 같습니다.\n\n- 숙주나물\n- 고사리\n- 도라지\n- 시금치\n- 무나물\n- 애호박\n- 육회 또는 쇠고기\n- 달걀이나 김가루\n\n진주비빔밥은 나물의 색과 모양을 살려 담는 데 중점을 두기 때문에, 전주비빔밥보다 **재료 하나하나의 맛과 식감이 비교적 또렷하게 느껴지는 편**입니다.\n\n맛은 **담백하고 깔끔하며, 숙주나물과 각종 나물의 산뜻함이 돋보이는 편**입니다. 육회가 올라가면 부드럽고 고소한 맛이 더해지지만, 전주비빔밥처럼 전체적으로 양념 맛이 강하고 진하게 느껴지기보다는 나물과 고기의 조화를 강조하는 경우가 많습니다.\n\n## 간단히 정리하면\n\n- **전주비빔밥**: 재료가 다양하고 양념과 참기름의 맛이 진함. 고소하고 풍성한 맛.\n- **진주비빔밥**: 나물의 색과 식감을 살리고 육회의 풍미를 강조함. 담백하고 깔끔한 맛.\n- **전주비빔밥을 좋아할 사람**: 진한 고추장 양념과 다양한 재료를 한꺼번에 비벼 먹는 것을 좋아하는 사람.\n- **진주비빔밥을 좋아할 사람**: 나물의 맛과 육회의 담백한 풍미를 비교적 선명하게 즐기고 싶은 사람.\n\n다만 오늘날에는 음식점마다 재료와 조리 방식이 달라서, 실제로는 전주식과 진주식의 차이가 상당히 줄어든 경우도 있습니다.',
 'Q3': "걸스데이(Girl’s Day)의 대표적인 히트곡은 다음과 같습니다.\n\n- **반짝반짝** (2011)  \n  걸스데이의 대중적 인지도를 크게 높인 곡으로, 밝고 발랄한 콘셉트가 돋보입니다.\n\n- **기대해** (2013)  \n  걸스데이의 대표곡 중 하나로, ‘멜빵춤’이 큰 화제를 모았습니다.\n\n- **여자 대통령** (2013)  \n  강렬하고 당당한 콘셉트의 곡으로 인기를 얻었습니다.\n\n- **Something** (2014)  \n  성숙하고 섹시한 분위기의 대표곡으로, 걸스데이의 이미지 변신을 보여준 곡입니다.\n\n- **Darling** (2014)  \n  밝고 상큼한 여름 노래로 많은 사랑을 받았습니다.\n\n- **링마벨(Ring My Bell)** (2015)  \n  경쾌한 멜로디와 중독성 있는 후렴구가 특징인 곡입니다.\n\n- **I'll Be Yours** (2017)  \n  걸스데이의 마지막 정규 앨범 타이틀곡으로, 세련된 팝 스타일의 곡입니다.\n\n- **잘해줘봐야** (2010)  \n  초기 걸스데이의 대표곡으로, 데뷔 초 귀엽고 발랄한 이미지를 보여줍니다.\n\n특히 대중적으로 가장 많이 언급되는 대표 히트곡은 **〈기대해〉, 〈여자 대통령〉, 〈Something〉, 〈Darling〉**입니다.",
 'Q4': '## 훈민정음 창제 배경과 세종대왕의 의의\n\n### 1. 훈민정음 창제의 배경\n\n훈민정음은 조선 세종 25년인 1443년에 창제되었고, 1446년에 《훈민정음》이라는 이름으로 반포되었습니다. 훈민정음이 만들어진 가장 중요한 배경은 당시 우리말과 한자 표기 체계 사이에 큰 차이가 있었기 때문입니다.\n\n조선 시대의 공식 문자로 사용되던 한자는 중국어를 바탕으로 만들어진 문자였습니다. 따라서 한국어의 어순과 문법, 소리를 정확하게 표현하기에는 한계가 있었습니다. 우리말을 적기 위해 이두나 향찰과 같은 표기법이 사용되기도 했지만, 배우기 어렵고 체계적이지 않아 일반 백성들이 쉽게 익히기 힘들었습니다.\n\n이러한 문자 생활의 어려움은 사회적 문제로도 이어졌습니다. 법률과 행정 문서를 읽지 못하는 백성들은 억울한 일을 당해도 자신의 사정을 알리기 어려웠고, 국가의 정책이나 유교적 윤리를 이해하는 데에도 한계가 있었습니다. 세종은 이러한 현실을 깊이 인식하고, 누구나 쉽게 배우고 사용할 수 있는 문자가 필요하다고 생각했습니다.\n\n또한 훈민정음 창제에는 우리 민족의 언어와 문화를 독자적으로 발전시키려는 의식도 담겨 있었습니다. 중국의 문자를 빌려 쓰는 데서 벗어나 우리말의 특징에 맞는 문자를 만들었다는 점에서 훈민정음은 문화적 자주성의 상징이라고 할 수 있습니다.\n\n### 2. 훈민정음의 특징\n\n훈민정음은 단순히 사용하기 쉬운 문자라는 점을 넘어, 매우 과학적이고 체계적으로 만들어졌습니다.\n\n- 자음은 발음 기관의 모양을 본떠 기본 글자를 만들었습니다.\n- 모음은 하늘, 땅, 사람을 뜻하는 ‘ㆍ, ㅡ, ㅣ’를 바탕으로 구성되었습니다.\n- 기본 글자에 획을 더하여 소리가 강해지는 원리를 나타냈습니다.\n- 글자를 음절 단위로 모아쓰기 때문에 한국어를 표현하기에 적합했습니다.\n\n이처럼 훈민정음은 한국어의 소리 체계를 분석하여 만들어진 문자였습니다. 《훈민정음 해례》에는 문자의 창제 원리와 사용법이 자세하게 설명되어 있어, 훈민정음이 매우 계획적이고 학문적인 과정을 거쳐 만들어졌음을 알 수 있습니다.\n\n### 3. 세종대왕의 의의\n\n세종대왕의 가장 큰 의의는 백성을 나라의 중요한 주체로 인식하고, 백성의 생활을 개선하기 위해 국가적 노력을 기울였다는 점에 있습니다. 훈민정음의 창제 목적을 밝힌 글에는 백성이 자신의 뜻을 제대로 표현하지 못하는 현실을 안타깝게 여기는 세종의 마음이 잘 나타나 있습니다.\n\n세종은 훈민정음뿐만 아니라 과학, 농업, 의학, 음악, 국방 등 다양한 분야의 발전에도 힘썼습니다. 측우기, 해시계, 물시계와 같은 과학 기구가 제작되었고, 농업 기술서와 의학서가 편찬되었습니다. 이러한 업적은 백성의 삶을 실질적으로 향상시키려는 정책과 연결되어 있습니다.\n\n특히 훈민정음은 지식과 정보의 독점을 완화했다는 점에서 큰 의미가 있습니다. 이전에는 문자와 지식이 주로 지배층에 집중되어 있었지만, 훈민정음은 일반 백성도 문자 생활에 참여할 수 있는 길을 열었습니다. 이후 한글은 교육, 문학, 종교, 행정 등 여러 분야에서 활용되며 우리 사회의 문화 발전에 큰 영향을 주었습니다.\n\n### 4. 결론\n\n훈민정음은 한자를 대신하기 위해 단순히 만들어진 문자가 아니라, 우리말을 정확하게 표현하고 백성들이 쉽게 배우도록 만든 독창적인 문자입니다. 그 창제 배경에는 당시 문자 생활의 불편함을 해결하고 백성의 의사소통과 권리를 보장하려는 세종대왕의 애민 정신이 있었습니다.\n\n세종대왕은 훈민정음 창제를 통해 문화적 자주성을 확립하고, 지식과 문화를 더 많은 사람에게 확산시키는 기반을 마련했습니다. 따라서 세종대왕의 의의는 뛰어난 정치적 업적뿐만 아니라, 백성을 위한 문자와 문화를 직접 창조하고 발전시킨 데 있다고 할 수 있습니다.',
 'Q5': '이순신 장군은 명량 해전에서 **울돌목의 좁은 물길과 거센 조류를 이용한 지형·조류 활용 전술**을 펼쳤습니다.\n\n주요 전술은 다음과 같습니다.\n\n1. **좁은 해협으로 일본 수군을 유인**\n   - 일본 수군의 많은 함선이 한꺼번에 움직이지 못하도록 울돌목이라는 협수로로 끌어들였습니다.\n   - 적의 수적 우세가 제대로 발휘되지 못하게 만든 것입니다.\n\n2. **조류의 흐름을 이용**\n   - 빠르게 방향이 바뀌는 울돌목의 조류를 파악하고, 조류가 조선 수군에게 유리하게 작용하는 시점을 활용했습니다.\n   - 일본 함선들이 조류에 휩쓸려 대열을 유지하지 못할 때 공격했습니다.\n\n3. **선두에서 직접 지휘하며 적의 선봉을 차단**\n   - 이순신은 대장선으로 적진 앞에 나아가 일본 수군의 공격을 받아내고, 적의 진격을 늦췄습니다.\n   - 이를 통해 부하 함선들이 전열을 정비할 시간을 벌었습니다.\n\n4. **화포와 판옥선의 성능을 활용한 집중 공격**\n   - 조선 수군은 일본 수군과 달리 원거리 화포 운용에 강점이 있었습니다.\n   - 적선이 가까이 접근하기 전에 화포를 발사하고, 튼튼한 판옥선으로 충돌과 근접전에도 대응했습니다.\n\n5. **적의 혼란을 확대하는 심리전**\n   - 좁은 물길에서 일본 함선들이 서로 부딪히거나 움직임을 제한받도록 만들고, 선봉이 무너지자 뒤따르던 함선들까지 혼란에 빠지게 했습니다.\n\n결국 명량 해전의 핵심은 **“적의 수가 많다는 약점을 좁은 해협과 조류를 이용해 상쇄하고, 화포와 지휘력을 바탕으로 적의 선봉을 집중 격파한 전술”**이라고 할 수 있습니다. 이를 통해 이순신은 불과 12척의 함선으로 훨씬 많은 일본 수군을 물리쳤습니다.',
 'Q6': '# 2024년 기후 변화 주요 지표와 한국의 탄소 중립 정책\n\n## 1. 2024년 세계 기후 변화 주요 지표\n\n2024년은 지구 기후 관측 역사상 매우 중요한 해였다. 여러 국제기관의 분석에 따르면, 2024년은 산업화 이전 대비 지구 평균기온이 가장 크게 상승한 해로 기록되었다.\n\n### 1) 지구 평균기온\n\n- 2024년 지구 평균기온은 산업화 이전 수준인 1850~1900년보다 약 **1.5~1.6℃ 높았던 것**으로 분석되었다.\n- 유럽연합 코페르니쿠스 기후변화서비스는 2024년을 관측 이래 가장 더운 해로 평가했으며, 연평균 기온이 산업화 이전보다 약 **1.60℃ 높은 수준**이라고 발표했다.\n- 세계기상기구도 2024년이 관측 사상 가장 더운 해였을 가능성이 매우 높다고 발표했다.\n- 다만 파리협정에서 말하는 **“1.5℃ 제한”은 단일 연도의 기온이 아니라 장기간 평균을 의미**한다. 따라서 2024년에 1.5℃를 넘었다고 해서 파리협정 목표가 공식적으로 폐기된 것은 아니지만, 장기 목표 달성이 매우 어려워졌다는 경고로 해석된다.\n\n### 2) 대기 중 이산화탄소 농도\n\n- 대기 중 이산화탄소 농도는 2024년에도 계속 증가하여 **420ppm을 크게 웃도는 수준**을 보였다.\n- 산업화 이전의 이산화탄소 농도는 약 280ppm 수준이었으므로, 현재 농도는 산업화 이전보다 약 50% 이상 높다.\n- 이산화탄소뿐 아니라 메탄과 아산화질소 농도도 증가하고 있어 온실가스 감축의 시급성이 커지고 있다.\n\n### 3) 해양 온도와 해수면 상승\n\n- 전 세계 해양은 2024년에도 기록적인 고수온을 보였다.\n- 해양은 인간이 배출한 열의 대부분을 흡수하고 있으며, 이에 따라 다음과 같은 현상이 나타나고 있다.\n  - 해양 열파 증가\n  - 산호 백화 현상 확대\n  - 해양 생태계와 어업 생산성 변화\n  - 해수면 상승 가속\n- 해수면은 빙하와 빙상 해빙, 해수의 열팽창으로 지속적으로 상승하고 있다. 해수면 상승 속도는 위성 관측이 시작된 이후 점점 빨라지는 추세다.\n\n### 4) 빙권 변화\n\n- 북극 해빙 면적은 장기 평균보다 낮은 수준을 유지했다.\n- 남극 해빙도 최근 몇 년간 이례적으로 낮은 수준을 보였다.\n- 그린란드와 산악 빙하의 질량 감소가 이어지고 있으며, 이는 장기적인 해수면 상승을 심화시키는 요인이다.\n\n### 5) 극한 기상 현상\n\n2024년에는 세계 곳곳에서 기후변화와 관련된 극한 현상이 발생했다.\n\n- 폭염과 열대야\n- 집중호우와 대규모 홍수\n- 대형 산불\n- 강력한 열대성 저기압\n- 장기 가뭄\n- 농업 생산량 감소와 식량 가격 불안\n\n기후변화는 단순히 평균기온이 상승하는 문제가 아니라, **극한기상의 빈도와 강도를 높이고 사회·경제적 피해를 확대하는 문제**로 나타나고 있다.\n\n---\n\n## 2. 2024년 한국의 기후 변화 상황\n\n한국도 기후변화의 영향을 뚜렷하게 경험하고 있다.\n\n### 1) 높은 기온과 폭염\n\n- 2024년 한국은 장기간의 폭염과 열대야를 경험했다.\n- 여름철 고온 현상이 장기화되었으며, 농업·전력수요·건강 피해가 증가했다.\n- 특히 도시 지역에서는 열섬현상으로 인해 체감온도가 더욱 높아졌다.\n\n### 2) 집중호우와 강수 패턴 변화\n\n- 짧은 시간에 많은 비가 내리는 집중호우가 반복되고 있다.\n- 반대로 지역에 따라 긴 건조 기간이 나타나 물 관리가 어려워지고 있다.\n- 강수량 자체보다 강수의 시기와 강도가 불규칙해지는 것이 중요한 문제다.\n\n### 3) 해수면과 해양 생태계 변화\n\n- 한반도 주변 해역의 수온 상승으로 어종 분포가 변하고 있다.\n- 아열대성 어종의 출현이 늘어나고, 기존 어업 생산성이 변화하고 있다.\n- 해안 지역은 해수면 상승과 태풍, 폭풍해일 위험에 더욱 취약해지고 있다.\n\n---\n\n# 3. 한국의 탄소 중립 정책\n\n## 1) 2050 탄소중립 목표\n\n한국은 **2050년까지 탄소중립을 달성한다는 국가 목표**를 설정하고 있다.\n\n탄소중립이란 온실가스 배출량을 최대한 줄이고, 불가피하게 배출되는 양은 산림흡수, 탄소 포집·저장, 국제 감축 등을 통해 상쇄하여 순배출량을 0으로 만드는 것을 의미한다.\n\n한국의 탄소중립 정책은 다음과 같은 법과 계획을 기반으로 한다.\n\n- 「기후위기 대응을 위한 탄소중립·녹색성장 기본법」\n- 2050 탄소중립 시나리오\n- 국가 탄소중립·녹색성장 기본계획\n- 국가 온실가스 감축목표, NDC\n- 온실가스 배출권거래제\n- 기후대응기금\n\n## 2) 2030 국가 온실가스 감축목표\n\n한국은 2030년까지 온실가스 배출량을 **2018년 대비 40% 감축**한다는 목표를 국제사회에 제출했다.\n\n부문별로는 대체로 다음과 같은 방향이 제시되어 있다.\n\n- 전환 부문: 석탄발전 축소, 재생에너지와 원자력 확대\n- 산업 부문: 에너지 효율 향상, 저탄소 공정 도입\n- 건물 부문: 에너지 효율 개선과 친환경 냉난방 확대\n- 수송 부문: 전기차와 수소차 확대\n- 농축수산 부문: 메탄·아산화질소 감축\n- 폐기물 부문: 재활용 확대와 매립·소각 감축\n- 흡수원 부문: 산림과 습지 등 탄소흡수원 확충\n- 수소 부문: 청정수소 생산과 활용 확대\n\n## 3) 전력 부문의 주요 정책\n\n전력 부문은 한국 온실가스 감축의 핵심 분야다.\n\n### 재생에너지 확대\n\n- 태양광과 풍력 발전을 확대한다.\n- 해상풍력과 분산형 전원 개발을 추진한다.\n- 재생에너지의 간헐성을 보완하기 위해 에너지저장장치와 전력망을 확충한다.\n\n### 원자력 활용\n\n- 정부는 원자력을 무탄소 전원으로 보고 원전의 안정적 운영과 신규 원전 활용을 추진하고 있다.\n- 원자력 확대는 전력 부문의 탄소배출을 줄이는 데 도움이 될 수 있지만, 안전성·사용후핵연료·지역 수용성 문제가 함께 논의되어야 한다.\n\n### 석탄발전 감축\n\n- 노후 석탄발전소의 폐쇄 또는 전환이 추진되고 있다.\n- 다만 전력수요 증가와 산업 경쟁력 문제로 인해 석탄발전 감축 속도와 방식에 대한 논쟁이 계속되고 있다.\n\n## 4) 산업 부문의 탄소 감축\n\n한국은 제조업과 수출 산업의 비중이 높기 때문에 산업 부문의 감축이 특히 중요하다.\n\n주요 정책은 다음과 같다.\n\n- 철강산업의 수소환원제철 도입\n- 석유화학산업의 원료 전환과 공정 효율화\n- 시멘트산업의 연료 전환과 탄소 포집\n- 산업단지의 에너지 효율 개선\n- 기업의 재생에너지 사용 확대\n- 중소기업 대상 탄소 감축 지원\n- 탄소 포집·활용·저장 기술 개발\n\n그러나 산업 부문은 기술개발 비용과 국제 경쟁력 문제 때문에 감축 속도가 상대적으로 느릴 수 있다.\n\n## 5) 수송 부문의 친환경 전환\n\n한국 정부는 수송 부문의 온실가스 감축을 위해 다음 정책을 추진하고 있다.\n\n- 전기자동차 보급 확대\n- 수소전기차 및 수소 상용차 개발\n- 전기차 충전 인프라 확충\n- 대중교통과 철도 이용 확대\n- 친환경 선박과 항공연료 개발\n- 내연기관 차량의 배출 기준 강화\n\n다만 2024년에는 전기차 판매 증가세 둔화, 충전 인프라 부족, 배터리 안전성에 대한 우려 등이 과제로 제기되었다.\n\n## 6) 건물과 도시 부문의 정책\n\n건물에서 사용하는 냉난방 에너지를 줄이는 것도 탄소중립의 중요한 수단이다.\n\n- 제로에너지건축물 확대\n- 건물 단열 성능 강화\n- 고효율 냉난방기 보급\n- 공공건축물 그린리모델링\n- 지역 냉난방과 재생에너지 활용\n- 스마트 전력관리 시스템 보급\n\n특히 기존 건물의 에너지 효율을 개선하는 **그린리모델링**이 중요한 정책으로 평가된다.\n\n## 7) 배출권거래제와 기후대응기금\n\n### 배출권거래제\n\n한국은 일정 규모 이상의 기업을 대상으로 온실가스 배출권거래제를 운영하고 있다.\n\n기업은 배출허용량보다 적게 배출하면 남은 배출권을 판매할 수 있고, 배출량이 많으면 배출권을 구매해야 한다. 이를 통해 기업이 온실가스 감축에 투자하도록 유도한다.\n\n하지만 다음과 같은 한계도 있다.\n\n- 배출권 가격이 충분히 높지 않을 수 있음\n- 무상할당 비중이 높다는 지적\n- 산업별 감축 책임의 형평성 문제\n- 중소기업의 대응 역량 부족\n\n### 기후대응기금\n\n정부는 기후대응기금을 활용하여 다음 사업을 지원하고 있다.\n\n- 온실가스 감축 기술 개발\n- 산업 전환 지원\n- 취약계층 보호\n- 지역 기후위기 대응\n- 녹색산업 육성\n- 기후재난 예방과 적응 사업\n\n---\n\n# 4. 2024년 한국 탄소중립 정책의 주요 쟁점\n\n## 1) 2030년 목표 달성 가능성\n\n2018년 대비 40% 감축은 상당히 높은 목표지만, 실제 달성을 위해서는 전력·산업·수송 부문의 빠른 전환이 필요하다.\n\n특히 다음 문제가 있다.\n\n- 산업 부문의 높은 에너지 사용량\n- 석탄발전 감축과 전력수요 증가의 충돌\n- 재생에너지 확대를 위한 입지와 송전망 부족\n- 기업의 감축 비용 증가\n- 지역별 에너지 전환 격차\n\n## 2) 2030년 이후 감축 경로의 불확실성\n\n2024년 헌법재판소는 정부의 탄소중립 관련 법률이 **2031년 이후의 온실가스 감축 목표를 충분히 제시하지 않은 점**에 대해 헌법에 합치되지 않는다는 취지의 결정을 내렸다.\n\n이는 단순히 2030년 목표만 제시할 것이 아니라, 2030년 이후 2040년과 2050년까지의 구체적이고 연속적인 감축 경로를 마련해야 한다는 의미로 평가된다.\n\n## 3) 정의로운 전환\n\n탄소중립 과정에서 석탄발전소, 내연기관차, 탄소 다배출 산업이 축소되면 특정 지역과 노동자가 큰 영향을 받을 수 있다.\n\n따라서 다음 정책이 필요하다.\n\n- 노동자 재교육과 전직 지원\n- 산업전환 지역 지원\n- 저소득층 에너지 비용 보조\n- 농어촌과 지역사회의 참여 확대\n- 탄소중립 정책에 대한 사회적 합의\n\n## 4) 기후변화 적응 정책 강화\n\n탄소 감축만으로는 이미 발생하고 있는 기후 피해를 막을 수 없다. 따라서 다음과 같은 적응정책도 필요하다.\n\n- 폭염 쉼터와 취약계층 보호\n- 도시 배수시설 개선\n- 산불과 산사태 대응체계 강화\n- 농작물 품종과 재배 시기 조정\n- 해안 방재시설 확충\n- 기후재난 보험과 피해 지원 확대\n\n---\n\n# 5. 종합 평가\n\n2024년은 기후변화가 미래의 문제가 아니라 현재 진행 중인 현실이라는 사실을 보여준 해였다. 지구 평균기온, 해양 열함량, 해수면, 극한기상 등 주요 지표가 악화되었고, 한국 역시 폭염·집중호우·해양 생태계 변화의 영향을 크게 받았다.\n\n한국은 2050년 탄소중립과 2030년 온실가스 40% 감축이라는 목표를 세웠으며, 재생에너지·원자력·전기차·수소·배출권거래제·기후대응기금 등을 활용해 정책을 추진하고 있다.\n\n그러나 목표 달성을 위해서는 다음 조건이 중요하다.\n\n1. 2030년 이후까지 이어지는 구체적인 감축 경로 마련  \n2. 재생에너지와 전력망의 확대  \n3. 산업 부문의 실질적인 기술 전환  \n4. 석탄발전 감축과 전력수요 관리  \n5. 취약계층과 노동자를 보호하는 정의로운 전환  \n6. 탄소 감축과 함께 기후재난 적응정책 강화  \n\n결국 한국의 탄소중립 정책은 선언적인 목표를 넘어, **실제 온실가스 배출량을 줄이고 사회적 비용을 공정하게 분담하는 실행 체계**를 갖추는 것이 핵심 과제라고 할 수 있다.',
 'Q7': '## 한국 AI 윤리 이슈와 관련 정책 사례\n\n한국의 AI 윤리 논의는 크게 **개인정보 보호, 차별과 공정성, 딥페이크와 허위정보, 안전성·책임성, 저작권, 노동과 교육** 문제를 중심으로 전개되고 있습니다.\n\n### 1. 개인정보 침해와 감시\n\n#### 주요 이슈\n- 생성형 AI 학습 과정에서 개인정보가 무단으로 수집될 가능성\n- 얼굴·음성·행동 데이터의 과도한 수집\n- 공공기관이나 기업의 AI CCTV, 안면인식 기술 활용에 따른 사생활 침해\n- AI가 개인정보를 기억하거나 재생산하는 문제\n\n#### 관련 정책·사례\n- **개인정보보호위원회의 AI 관련 개인정보 보호 안내서**\n  - AI 개발·학습·서비스 제공 단계별로 개인정보 최소 수집, 가명처리, 안전성 확보 등을 요구\n- **개인정보보호법**\n  - 개인정보 수집·이용의 법적 근거와 정보주체의 권리 규정\n  - 자동화된 의사결정에 대해 설명 요구나 이의 제기와 관련된 권리 강화\n- 예를 들어 기업이 고객 상담 데이터를 생성형 AI 학습에 활용하려면, 개인정보 포함 여부와 이용 목적, 보관 기간 등을 검토해야 합니다.\n\n---\n\n### 2. 알고리즘 편향과 차별\n\n#### 주요 이슈\nAI가 학습한 데이터에 성별·연령·지역·장애·인종 등에 대한 편견이 포함되어 있으면 다음과 같은 문제가 발생할 수 있습니다.\n\n- 채용 AI가 특정 성별이나 학교 출신을 선호\n- 금융 AI가 특정 지역이나 연령층의 대출을 불리하게 평가\n- 복지 대상자 선정 과정에서 취약계층이 부당하게 제외\n- 얼굴인식 기술이 피부색이나 성별에 따라 정확도가 달라지는 문제\n\n#### 관련 정책·사례\n- 정부는 공공기관 AI 사업에서 **공정성, 차별 방지, 설명 가능성**을 검토하도록 권고하고 있습니다.\n- 공공기관이 복지·채용·민원 처리에 AI를 활용할 경우, 최종 결정을 AI에만 맡기기보다 **인간의 검토 절차**를 두는 방식이 제시됩니다.\n- 기업 역시 알고리즘 영향평가, 편향 점검, 데이터 대표성 검토 등을 수행할 필요가 있습니다.\n\n---\n\n### 3. 딥페이크와 허위정보\n\n#### 주요 이슈\n- 유명인이나 일반인의 얼굴을 합성한 가짜 영상 유포\n- 비동의 성적 딥페이크 제작·유통\n- 선거 기간 중 가짜 음성·영상 확산\n- 생성형 AI를 이용한 사기, 보이스피싱, 명예훼손\n\n#### 관련 정책·사례\n- 한국은 딥페이크 성범죄에 대해 처벌을 강화하고 있으며, 제작·유포뿐 아니라 소지·시청 행위까지 규제 범위를 확대하는 방향으로 제도를 정비했습니다.\n- 플랫폼 사업자에게 불법 합성물의 삭제·차단과 피해자 보호 조치가 요구됩니다.\n- 선거와 관련해서는 AI로 만든 허위 영상이나 음성의 제작·유포를 제한하는 공직선거법상 규제가 적용될 수 있습니다.\n- 정부와 플랫폼은 AI 생성물에 워터마크나 메타데이터를 표시하는 방안도 검토하고 있습니다.\n\n---\n\n### 4. 생성형 AI의 허위 답변과 안전성\n\n#### 주요 이슈\n생성형 AI는 실제로 존재하지 않는 사실을 그럴듯하게 만들어내는 **환각 현상**이 발생할 수 있습니다.\n\n- 법률·의료·금융 분야에서 잘못된 정보 제공\n- 가짜 판례나 논문 생성\n- 재난·안보 상황에서 부정확한 정보 확산\n- 아동이나 청소년에게 유해한 콘텐츠 제공\n\n#### 관련 정책·사례\n- 정부는 생성형 AI 서비스에 대해 **투명성, 안전성, 이용자 보호** 원칙을 제시하고 있습니다.\n- 고위험 분야에서는 AI의 결과를 사람이 검토하고, 오류 발생 시 책임 주체를 명확히 하는 것이 중요합니다.\n- 금융·의료·법률 서비스에서는 AI가 참고자료를 제공하더라도 최종 판단은 자격을 갖춘 전문가가 하도록 하는 방식이 일반적으로 권고됩니다.\n- 공공기관의 AI 도입 시에는 사전 위험평가와 보안성 검토가 요구될 수 있습니다.\n\n---\n\n### 5. 저작권과 창작자 권리\n\n#### 주요 이슈\n- 생성형 AI가 인터넷상의 이미지·글·음악을 학습에 활용하는 과정에서 저작권 침해 여부\n- AI가 만든 결과물의 저작권 인정 여부\n- 기존 작가의 화풍을 모방하는 문제\n- 언론 기사나 콘텐츠가 AI 학습에 무단 사용되는 문제\n\n#### 관련 정책·사례\n- 한국에서는 저작권법상 인간의 창작적 기여가 없는 순수 AI 산출물의 저작권 인정 여부가 제한적으로 해석됩니다.\n- AI가 생성한 결과물이라도 인간이 상당한 창작적 수정·편집을 했다면 그 부분에 대해서는 저작권이 인정될 가능성이 있습니다.\n- 정부는 AI 학습 데이터 이용과 관련해 저작권자와 AI 기업 간의 합법적 이용, 보상, 라이선스 체계 마련을 논의하고 있습니다.\n- 콘텐츠 제작 현장에서는 AI 사용 여부를 표시하거나, 원작자 동의를 받는 윤리 기준이 제시되고 있습니다.\n\n---\n\n### 6. 노동시장 변화와 책임 있는 자동화\n\n#### 주요 이슈\n- AI로 인한 일자리 감소 또는 직무 재편\n- 배달·운송·플랫폼 노동자에 대한 알고리즘 통제\n- AI가 노동자의 성과와 근무 태도를 과도하게 감시\n- AI 면접과 자동 평가의 공정성 문제\n\n#### 관련 정책·사례\n- 정부는 AI·디지털 전환에 대응하기 위해 재교육과 직업훈련 확대 정책을 추진하고 있습니다.\n- 기업이 AI를 이용해 채용·인사평가를 할 경우 지원자에게 평가 방식과 개인정보 처리 내용을 알리고, 오류에 대한 이의 제기 기회를 제공할 필요가 있습니다.\n- 근로자에게 불리한 인사 결정을 AI가 단독으로 내리지 않도록 인간의 재검토 절차를 두는 것이 권고됩니다.\n\n---\n\n## 한국의 주요 AI 윤리·정책 사례\n\n### 1. 「인공지능 윤리기준」 제정\n\n한국 정부는 2020년 인공지능 윤리기준을 제시했습니다. 주요 원칙은 다음과 같습니다.\n\n1. **인간 존엄성**\n2. **사회의 공공선**\n3. **기술의 합목적성**\n\n이를 구체화하면 다음과 같은 실천 원칙으로 연결됩니다.\n\n- 인권 보장\n- 프라이버시 보호\n- 다양성 존중\n- 침해 금지\n- 공공성\n- 연대성\n- 데이터 관리\n- 책임성\n- 안전성\n- 투명성\n\n이 기준은 법적 처벌 규정보다는 기업·공공기관이 AI를 개발하고 운영할 때 참고하는 윤리 원칙의 성격이 강합니다.\n\n---\n\n### 2. 인공지능 기본법\n\n한국은 「인공지능 발전과 신뢰 기반 조성 등에 관한 기본법」을 마련하여 AI 산업 발전과 신뢰성 확보를 함께 추진하고 있습니다.\n\n주요 내용은 다음과 같습니다.\n\n- 국가 AI 정책을 조정하는 체계 마련\n- 고영향 인공지능에 대한 안전성·투명성 관리\n- 생성형 AI와 고영향 AI에 대한 이용자 고지\n- AI 사업자의 안전관리와 위험 대응\n- AI 산업 진흥과 연구개발 지원\n- 이용자 보호 및 피해 구제 체계 마련\n\n예를 들어 의료, 금융, 채용, 교육, 공공서비스처럼 개인의 권리와 생활에 큰 영향을 주는 AI는 일반적인 추천 서비스보다 더 엄격한 관리가 필요하다는 접근입니다.\n\n---\n\n### 3. 개인정보보호위원회의 AI 개인정보 보호 정책\n\n개인정보보호위원회는 AI 개발 단계에서 다음 사항을 강조하고 있습니다.\n\n- 필요한 개인정보만 수집\n- 개인정보와 민감정보의 적법한 처리\n- 가명정보·익명정보 활용\n- 학습 데이터의 출처와 처리 목적 관리\n- 이용자에게 개인정보 처리 사실 고지\n- AI 모델에서 개인정보가 재생산되지 않도록 점검\n- 개인정보 침해 발생 시 신고와 피해 구제\n\n이는 생성형 AI 서비스를 개발하는 기업뿐 아니라 사내 업무용 AI를 도입하는 기업에도 적용될 수 있는 원칙입니다.\n\n---\n\n### 4. 공공기관의 AI 윤리 영향평가\n\n공공서비스에 AI를 도입할 때는 다음과 같은 항목을 사전에 검토하는 방식이 활용되고 있습니다.\n\n- 누구에게 영향을 주는가\n- 특정 집단이 불리해질 가능성은 없는가\n- AI 결정에 대해 설명할 수 있는가\n- 오류 발생 시 책임자는 누구인가\n- 사람이 결과를 재검토할 수 있는가\n- 개인정보와 보안 문제가 없는가\n\n예를 들어 복지 대상자 선별 AI를 도입할 경우, AI가 탈락시킨 사람에게 결과의 이유를 설명하고 이의를 제기할 수 있는 절차를 마련해야 합니다.\n\n---\n\n## 정리\n\n한국의 AI 윤리 정책은 단순히 “AI 사용을 금지”하는 방향보다는 다음 네 가지를 함께 추구하고 있습니다.\n\n1. **AI 산업과 기술 발전 지원**\n2. **개인정보와 인권 보호**\n3. **고위험 AI에 대한 투명성과 책임성 강화**\n4. **딥페이크·허위정보·차별 등 구체적인 피해 방지**\n\n앞으로 특히 중요한 과제는 **AI 의사결정에 대한 설명권**, **생성형 AI 결과물 표시**, **저작권자와 데이터 제공자에 대한 보상**, **AI 피해 발생 시 책임 주체 확립**, **취약계층 보호**가 될 것으로 보입니다.',
 'Q8': '## 서울 지하철 환승 시 T-money 사용 방법\n\n### 1. 지하철을 탈 때\n1. 개찰구의 교통카드 단말기에 T-money 카드를 댑니다.\n2. “삑” 소리가 나고 개찰구가 열리면 통과합니다.\n3. 지하철 노선이 달라도 **개찰구 밖으로 나가지 않고 환승 통로를 이용하면 별도로 카드를 다시 찍지 않습니다.**\n\n예를 들어 2호선에서 4호선으로 갈아탈 때, 안내 표지판을 따라 환승하면 됩니다.\n\n### 2. 지하철에서 내릴 때\n목적지 역 개찰구에서 T-money 카드를 다시 댑니다.\n\n- 승차 시 태그: 요금 계산 시작\n- 하차 시 태그: 최종 요금 계산 및 차감\n- 하차 태그를 하지 않으면 이용 기록이 정상 처리되지 않아 이후 이용에 문제가 생길 수 있습니다.\n\n### 3. 버스와 지하철을 환승할 때\nT-money를 사용하면 버스와 지하철 사이에 환승 할인 또는 통합 요금이 적용될 수 있습니다.\n\n예시:\n\n- 버스 하차 후 지하철 승차\n- 지하철 하차 후 버스 승차\n- 버스에서 다른 버스로 환승\n\n이때는 다음과 같이 카드를 사용합니다.\n\n- 버스: 탈 때와 내릴 때 모두 태그\n- 지하철: 들어갈 때와 나올 때 모두 태그\n\n환승 할인 적용을 위해 버스에서 내릴 때 반드시 하차 태그를 해야 합니다.\n\n### 4. 환승 시간\n일반적으로 대중교통 하차 후 일정 시간 이내에 다른 교통수단을 이용해야 환승 할인이 적용됩니다.\n\n- 보통 하차 후 **30분 이내**\n- 밤 시간대에는 환승 가능 시간이 더 길어질 수 있음\n- 환승 가능 횟수와 거리에 따라 추가 요금이 발생할 수 있음\n\n정확한 적용 기준은 이용 시간, 교통수단, 이동 거리 등에 따라 달라질 수 있습니다.\n\n### 5. 주의할 점\n\n- 한 장의 T-money 카드로 여러 명이 동시에 지하철을 이용할 수는 없습니다. 지하철은 승객 1명당 카드 1장이 필요합니다.\n- 카드를 지갑에서 꺼내 단말기에 직접 대는 것이 좋습니다.\n- 승차할 때와 하차할 때 반드시 같은 카드를 사용해야 합니다.\n- 개찰구 밖으로 나갔다가 다시 들어오면 환승이 아니라 새로운 승차로 처리될 수 있습니다.\n- 잔액이 부족하면 개찰구를 통과할 수 없으므로 미리 충전하는 것이 좋습니다.\n- 모바일 T-money, 실물 T-money, 외국인용 교통카드 등도 기본적으로 같은 방식으로 사용할 수 있습니다.\n\n### 간단한 예시\n\n**서울역에서 1호선을 타고 동대문역사문화공원역에서 4호선으로 환승한 뒤 명동역에서 내리는 경우**\n\n1. 서울역에서 T-money 태그\n2. 환승 통로를 통해 4호선으로 이동\n3. 별도 태그 없이 4호선 이용\n4. 명동역에서 T-money 태그 후 하차\n\n즉, **지하철 노선 간 환승은 개찰구 밖으로 나가지 않는 한 카드를 다시 찍지 않고, 최종 목적지에서만 하차 태그를 하면 됩니다.**',

In [18]:
import pandas as pd

pd.set_option('display.max_colwidth',None)  # 긴 텍스트도 생갹 없이 표시

hyde_df = pd.DataFrame({
    'query_id' : list(hyde_pseudo.keys()),  # qid 리스트
    'query_text': queries_df['query_text'], # 원본 질문 Series
    'pseudo_answer' : list(hyde_pseudo.values()) # 가상 질문 리스트
})

hyde_df.head()

,query_id,query_text,pseudo_answer
0,Q1,제주도 올레길 트레킹 코스 추천,"제주 올레길은 코스마다 풍경과 난이도가 달라서 여행 일정과 체력에 맞춰 선택하는 것이 좋습니다. 처음 걷는다면 아래 코스를 추천합니다.\n\n## 1. 가장 무난한 해안 풍경: 올레길 6코스\n- **구간:** 쇠소깍~제주올레여행자센터\n- **거리:** 약 11km\n- **소요 시간:** 4~5시간\n- **난이도:** 쉬움\n- **주요 풍경:** 쇠소깍, 검은모래 해변, 정방폭포 주변, 서귀포 해안\n- **추천 이유:** 비교적 짧고 대중교통과 식당 이용이 편리합니다. 바다와 마을 풍경을 균형 있게 볼 수 있어 첫 올레길로 좋습니다.\n\n## 2. 제주다운 해안 절경: 올레길 7코스\n- **구간:** 외돌개~월평\n- **거리:** 약 17.7km\n- **소요 시간:** 5~6시간\n- **난이도:** 보통\n- **주요 풍경:** 외돌개, 황우지해안, 법환포구, 월평해안\n- **추천 이유:** 제주 올레길 중 가장 유명한 코스 중 하나입니다. 해안 절벽과 바다 풍경이 아름답고 사진 찍기 좋습니다.\n- **주의:** 전체 코스가 길게 느껴질 수 있어 체력이 부담되면 외돌개~법환포구 구간만 걸어도 좋습니다.\n\n## 3. 성산일출봉을 만나는 코스: 올레길 1코스\n- **구간:** 시흥초등학교~광치기해변\n- **거리:** 약 15km\n- **소요 시간:** 4~5시간\n- **난이도:** 보통\n- **주요 풍경:** 말미오름, 알오름, 성산일출봉, 섭지코지 인근 풍경\n- **추천 이유:** 오름과 바다를 한 번에 경험할 수 있습니다. 날씨가 맑으면 성산일출봉 주변 경관이 특히 아름답습니다.\n- **주의:** 오름 구간은 바람이 강하거나 미끄러울 수 있습니다.\n\n## 4. 바다와 송악산 풍경: 올레길 10코스\n- **구간:** 화순금모래해변~하모체육공원\n- **거리:** 약 15.6km\n- **소요 시간:** 5시간 안팎\n- **난이도:** 보통\n- **주요 풍경:** 산방산, 용머리해안 주변, 송악산, 모슬포 해안\n- **추천 이유:** 제주 서남부의 대표적인 풍경을 볼 수 있는 코스입니다. 산방산과 송악산을 배경으로 걷는 길이 인상적입니다.\n- **주의:** 용머리해안은 기상과 물때에 따라 입장이 제한될 수 있습니다.\n\n## 5. 짧고 여유로운 숲길: 올레길 14-1코스\n- **구간:** 저지예술정보화마을~무릉외갓집\n- **거리:** 약 9km\n- **소요 시간:** 3~4시간\n- **난이도:** 쉬움~보통\n- **주요 풍경:** 곶자왈, 숲길, 밭길, 제주 중산간 마을\n- **추천 이유:** 바닷길보다 조용한 숲길을 선호한다면 좋습니다. 관광객이 비교적 적고 제주 중산간의 분위기를 느낄 수 있습니다.\n- **주의:** 숲길에서는 휴대전화 신호가 약한 구간이 있을 수 있으므로 이정표를 잘 확인해야 합니다.\n\n## 6. 제주 원도심과 해안 산책: 올레길 18코스\n- **구간:** 제주원도심~조천 만세동산\n- **거리:** 약 19km\n- **소요 시간:** 6시간 이상\n- **난이도:** 보통\n- **주요 풍경:** 제주항, 사라봉, 별도봉, 해안 마을, 조천 해안\n- **추천 이유:** 자연뿐 아니라 제주 도심과 역사적인 장소도 함께 볼 수 있습니다.\n- **주의:** 거리가 긴 편이라 하루 일정을 넉넉히 잡는 것이 좋습니다.\n\n## 여행 일정별 추천\n\n### 반나절만 걸을 때\n- 올레길 6코스 일부\n- 올레길 7코스 외돌개~법환포구\n- 올레길 9코스 대평포구 주변\n\n### 하루 동안 대표 풍경을 보고 싶을 때\n- 올레길 7코스\n- 올레길 10코스\n- 올레길 1코스\n\n### 조용한 길을 선호할 때\n- 올레길 14-1코스\n- 올레길 13코스\n- 올레길 18코스 일부\n\n### 대중교통을 이용할 때\n서귀포 중심 숙소라면 **6코스와 7코스**가 편리하고, 성산·모슬포 쪽 숙소라면 각각 **1코스와 10코스**를 선택하기 좋습니다. 코스 시작점과 종점의 버스 운행 간격이 길 수 있으므로 출발 전 교통편을 확인하는 것이 좋습니다.\n\n## 준비물과 주의사항\n- 미끄럽지 않은 트레킹화 또는 운동화\n- 물과 간단한 간식\n- 모자, 자외선 차단제, 우비\n- 바람막이 재킷\n- 휴대전화 보조배터리\n- 공식 올레길 앱 또는 코스 안내 지도\n\n제주도는 날씨가 빠르게 바뀌고 바람이 강한 날이 많습니다. 특히 오름과 해안 절벽 구간은 비가 온 뒤 미끄러울 수 있으므로 출발 전 날씨와 코스 통제 여부를 확인하세요.\n\n**처음 걷는다면 개인적으로는 올레길 6코스**, 제주다운 절경을 가장 많이 보고 싶다면 **7코스**, 성산일출봉까지 함께 보고 싶다면 **1코스**를 추천합니다."
1,Q2,전주 비빔밥 vs 진주 비빔밥 재료 및 맛 차이,"## 전주비빔밥 vs 진주비빔밥\n\n두 음식 모두 여러 가지 나물과 고기, 양념을 밥에 섞어 먹는 전통 비빔밥이지만, **전주비빔밥은 재료의 다양성과 고소하고 진한 양념 맛**, **진주비빔밥은 색감과 나물의 담백함, 육회의 풍미**가 상대적으로 두드러집니다. 다만 가게와 조리법에 따라 차이가 있을 수 있습니다.\n\n| 구분 | 전주비빔밥 | 진주비빔밥 |\n|---|---|---|\n| 대표 특징 | 다양한 나물과 육회, 황포묵을 올림 | 여러 색의 나물을 꽃처럼 담는 ‘칠보화반’ |\n| 주요 재료 | 콩나물, 시금치, 고사리, 도라지, 표고버섯, 애호박, 무나물, 육회, 황포묵, 달걀 등 | 숙주나물, 고사리, 도라지, 시금치, 무나물, 애호박, 육회 등 |\n| 밥 | 쌀밥 또는 쇠고기 육수·콩나물 등을 활용한 밥 | 비교적 담백한 밥에 여러 나물을 곁들이는 방식 |\n| 양념 | 고추장, 참기름, 깨, 마늘 등 | 고추장과 참기름을 사용하지만 재료 본연의 맛을 살리는 편 |\n| 곁들임 | 콩나물국이 자주 함께 나옴 | 선짓국이나 국물을 곁들이는 경우가 있음 |\n| 맛의 인상 | 고소하고 진하며 감칠맛이 풍부함 | 담백하고 깔끔하며 나물과 육회의 맛이 선명함 |\n\n### 1. 전주비빔밥의 재료와 맛\n\n전주비빔밥은 보통 다음과 같은 재료를 사용합니다.\n\n- 여러 가지 나물\n- 콩나물\n- 육회 또는 익힌 쇠고기\n- 황포묵\n- 달걀\n- 표고버섯\n- 고추장\n- 참기름과 깨\n\n전주비빔밥의 특징은 **재료의 종류가 많고 각각의 나물을 따로 정성스럽게 무친다**는 점입니다. 특히 콩나물과 황포묵이 들어가 아삭하거나 부드러운 식감이 함께 느껴집니다.\n\n맛은 대체로 **고소하고 진하며 감칠맛이 풍부한 편**입니다. 고추장과 참기름을 넣고 비비면 양념 맛이 전체적으로 잘 어우러지고, 육회나 쇠고기가 들어갈 경우 고기 특유의 풍미도 강하게 느껴집니다.\n\n### 2. 진주비빔밥의 재료와 맛\n\n진주비빔밥은 ‘**칠보화반**’이라고도 불립니다. 여러 가지 나물을 일곱 가지 색처럼 아름답게 배치해 담아내는 것이 특징입니다.\n\n주로 들어가는 재료는 다음과 같습니다.\n\n- 숙주나물\n- 고사리\n- 도라지\n- 시금치\n- 무나물\n- 애호박\n- 육회 또는 쇠고기\n- 달걀이나 김가루\n\n진주비빔밥은 나물의 색과 모양을 살려 담는 데 중점을 두기 때문에, 전주비빔밥보다 **재료 하나하나의 맛과 식감이 비교적 또렷하게 느껴지는 편**입니다.\n\n맛은 **담백하고 깔끔하며, 숙주나물과 각종 나물의 산뜻함이 돋보이는 편**입니다. 육회가 올라가면 부드럽고 고소한 맛이 더해지지만, 전주비빔밥처럼 전체적으로 양념 맛이 강하고 진하게 느껴지기보다는 나물과 고기의 조화를 강조하는 경우가 많습니다.\n\n## 간단히 정리하면\n\n- **전주비빔밥**: 재료가 다양하고 양념과 참기름의 맛이 진함. 고소하고 풍성한 맛.\n- **진주비빔밥**: 나물의 색과 식감을 살리고 육회의 풍미를 강조함. 담백하고 깔끔한 맛.\n- **전주비빔밥을 좋아할 사람**: 진한 고추장 양념과 다양한 재료를 한꺼번에 비벼 먹는 것을 좋아하는 사람.\n- **진주비빔밥을 좋아할 사람**: 나물의 맛과 육회의 담백한 풍미를 비교적 선명하게 즐기고 싶은 사람.\n\n다만 오늘날에는 음식점마다 재료와 조리 방식이 달라서, 실제로는 전주식과 진주식의 차이가 상당히 줄어든 경우도 있습니다."
2,Q3,걸스데이 대표 히트곡 목록 알려줘,"걸스데이(Girl’s Day)의 대표적인 히트곡은 다음과 같습니다.\n\n- **반짝반짝** (2011) \n 걸스데이의 대중적 인지도를 크게 높인 곡으로, 밝고 발랄한 콘셉트가 돋보입니다.\n\n- **기대해** (2013) \n 걸스데이의 대표곡 중 하나로, ‘멜빵춤’이 큰 화제를 모았습니다.\n\n- **여자 대통령** (2013) \n 강렬하고 당당한 콘셉트의 곡으로 인기를 얻었습니다.\n\n- **Something** (2014) \n 성숙하고 섹시한 분위기의 대표곡으로, 걸스데이의 이미지 변신을 보여준 곡입니다.\n\n- **Darling** (2014) \n 밝고 상큼한 여름 노래로 많은 사랑을 받았습니다.\n\n- **링마벨(Ring My Bell)** (2015) \n 경쾌한 멜로디와 중독성 있는 후렴구가 특징인 곡입니다.\n\n- **I'll Be Yours** (2017) \n 걸스데이의 마지막 정규 앨범 타이틀곡으로, 세련된 팝 스타일의 곡입니다.\n\n- **잘해줘봐야** (2010) \n 초기 걸스데이의 대표곡으로, 데뷔 초 귀엽고 발랄한 이미지를 보여줍니다.\n\n특히 대중적으로 가장 많이 언급되는 대표 히트곡은 **〈기대해〉, 〈여자 대통령〉, 〈Something〉, 〈Darling〉**입니다."
3,Q4,훈민정음 창제 배경과 세종대왕의 의의,"## 훈민정음 창제 배경과 세종대왕의 의의\n\n### 1. 훈민정음 창제의 배경\n\n훈민정음은 조선 세종 25년인 1443년에 창제되었고, 1446년에 《훈민정음》이라는 이름으로 반포되었습니다. 훈민정음이 만들어진 가장 중요한 배경은 당시 우리말과 한자 표기 체계 사이에 큰 차이가 있었기 때문입니다.\n\n조선 시대의 공식 문자로 사용되던 한자는 중국어를 바탕으로 만들어진 문자였습니다. 따라서 한국어의 어순과 문법, 소리를 정확하게 표현하기에는 한계가 있었습니다. 우리말을 적기 위해 이두나 향찰과 같은 표기법이 사용되기도 했지만, 배우기 어렵고 체계적이지 않아 일반 백성들이 쉽게 익히기 힘들었습니다.\n\n이러한 문자 생활의 어려움은 사회적 문제로도 이어졌습니다. 법률과 행정 문서를 읽지 못하는 백성들은 억울한 일을 당해도 자신의 사정을 알리기 어려웠고, 국가의 정책이나 유교적 윤리를 이해하는 데에도 한계가 있었습니다. 세종은 이러한 현실을 깊이 인식하고, 누구나 쉽게 배우고 사용할 수 있는 문자가 필요하다고 생각했습니다.\n\n또한 훈민정음 창제에는 우리 민족의 언어와 문화를 독자적으로 발전시키려는 의식도 담겨 있었습니다. 중국의 문자를 빌려 쓰는 데서 벗어나 우리말의 특징에 맞는 문자를 만들었다는 점에서 훈민정음은 문화적 자주성의 상징이라고 할 수 있습니다.\n\n### 2. 훈민정음의 특징\n\n훈민정음은 단순히 사용하기 쉬운 문자라는 점을 넘어, 매우 과학적이고 체계적으로 만들어졌습니다.\n\n- 자음은 발음 기관의 모양을 본떠 기본 글자를 만들었습니다.\n- 모음은 하늘, 땅, 사람을 뜻하는 ‘ㆍ, ㅡ, ㅣ’를 바탕으로 구성되었습니다.\n- 기본 글자에 획을 더하여 소리가 강해지는 원리를 나타냈습니다.\n- 글자를 음절 단위로 모아쓰기 때문에 한국어를 표현하기에 적합했습니다.\n\n이처럼 훈민정음은 한국어의 소리 체계를 분석하여 만들어진 문자였습니다. 《훈민정음 해례》에는 문자의 창제 원리와 사용법이 자세하게 설명되어 있어, 훈민정음이 매우 계획적이고 학문적인 과정을 거쳐 만들어졌음을 알 수 있습니다.\n\n### 3. 세종대왕의 의의\n\n세종대왕의 가장 큰 의의는 백성을 나라의 중요한 주체로 인식하고, 백성의 생활을 개선하기 위해 국가적 노력을 기울였다는 점에 있습니다. 훈민정음의 창제 목적을 밝힌 글에는 백성이 자신의 뜻을 제대로 표현하지 못하는 현실을 안타깝게 여기는 세종의 마음이 잘 나타나 있습니다.\n\n세종은 훈민정음뿐만 아니라 과학, 농업, 의학, 음악, 국방 등 다양한 분야의 발전에도 힘썼습니다. 측우기, 해시계, 물시계와 같은 과학 기구가 제작되었고, 농업 기술서와 의학서가 편찬되었습니다. 이러한 업적은 백성의 삶을 실질적으로 향상시키려는 정책과 연결되어 있습니다.\n\n특히 훈민정음은 지식과 정보의 독점을 완화했다는 점에서 큰 의미가 있습니다. 이전에는 문자와 지식이 주로 지배층에 집중되어 있었지만, 훈민정음은 일반 백성도 문자 생활에 참여할 수 있는 길을 열었습니다. 이후 한글은 교육, 문학, 종교, 행정 등 여러 분야에서 활용되며 우리 사회의 문화 발전에 큰 영향을 주었습니다.\n\n### 4. 결론\n\n훈민정음은 한자를 대신하기 위해 단순히 만들어진 문자가 아니라, 우리말을 정확하게 표현하고 백성들이 쉽게 배우도록 만든 독창적인 문자입니다. 그 창제 배경에는 당시 문자 생활의 불편함을 해결하고 백성의 의사소통과 권리를 보장하려는 세종대왕의 애민 정신이 있었습니다.\n\n세종대왕은 훈민정음 창제를 통해 문화적 자주성을 확립하고, 지식과 문화를 더 많은 사람에게 확산시키는 기반을 마련했습니다. 따라서 세종대왕의 의의는 뛰어난 정치적 업적뿐만 아니라, 백성을 위한 문자와 문화를 직접 창조하고 발전시킨 데 있다고 할 수 있습니다."
4,Q5,이순신 장군이 명량 해전에서 사용한 전술은 무엇인가?,"이순신 장군은 명량 해전에서 **울돌목의 좁은 물길과 거센 조류를 이용한 지형·조류 활용 전술**을 펼쳤습니다.\n\n주요 전술은 다음과 같습니다.\n\n1. **좁은 해협으로 일본 수군을 유인**\n - 일본 수군의 많은 함선이 한꺼번에 움직이지 못하도록 울돌목이라는 협수로로 끌어들였습니다.\n - 적의 수적 우세가 제대로 발휘되지 못하게 만든 것입니다.\n\n2. **조류의 흐름을 이용**\n - 빠르게 방향이 바뀌는 울돌목의 조류를 파악하고, 조류가 조선 수군에게 유리하게 작용하는 시점을 활용했습니다.\n - 일본 함선들이 조류에 휩쓸려 대열을 유지하지 못할 때 공격했습니다.\n\n3. **선두에서 직접 지휘하며 적의 선봉을 차단**\n - 이순신은 대장선으로 적진 앞에 나아가 일본 수군의 공격을 받아내고, 적의 진격을 늦췄습니다.\n - 이를 통해 부하 함선들이 전열을 정비할 시간을 벌었습니다.\n\n4. **화포와 판옥선의 성능을 활용한 집중 공격**\n - 조선 수군은 일본 수군과 달리 원거리 화포 운용에 강점이 있었습니다.\n - 적선이 가까이 접근하기 전에 화포를 발사하고, 튼튼한 판옥선으로 충돌과 근접전에도 대응했습니다.\n\n5. **적의 혼란을 확대하는 심리전**\n - 좁은 물길에서 일본 함선들이 서로 부딪히거나 움직임을 제한받도록 만들고, 선봉이 무너지자 뒤따르던 함선들까지 혼란에 빠지게 했습니다.\n\n결국 명량 해전의 핵심은 **“적의 수가 많다는 약점을 좁은 해협과 조류를 이용해 상쇄하고, 화포와 지휘력을 바탕으로 적의 선봉을 집중 격파한 전술”**이라고 할 수 있습니다. 이를 통해 이순신은 불과 12척의 함선으로 훨씬 많은 일본 수군을 물리쳤습니다."

### Hyde(가상답변) 기반 Dense검색 결과 수집

In [23]:
hyde_results = {}

for idx, row in tqdm(queries_df.iterrows()):
    qid = row['query_id']
    query_text = row['query_text']
    pseudo_answer = row['pseudo_answer']
    docs = vector_store.similarity_search(pseudo_answer,k=5)
    hyde_results[qid] = [doc.metadat['doc_id']for doc in docs]

hyde_results

0it [00:00, ?it/s]

KeyError: 'pseudo_answer'

In [ ]:
# Vector Store 검색 결과를 쿼리별로 수집

dense_results = {}   # qid별 BM25 검색 결과 저장 dict
for idx, row in queries_df.iterrows():
    qid = row['query_id']   # 쿼리 ID 추출
    query_text = row['query_text']  # 쿼리 문장
     # {qid : query_text와 가장 가까운 5개의 doc_id}
    docs = vector_store.similarity_search(query_text, top_k = 5)  
    dense_results[qid] = [doc.metadata['doc_id']for doc in docs]
dense_results

In [24]:
import numpy as np

def parse_relevant(relevant_str) -> dict[str,int]:
    """ 
    참조문서 답안 문자열을 dict로 파싱하는 함수

    relevant_str = "D1=3;D4=1;D30=1" -> {'D1' :3, 'D2':1, 'D30':1}
    """

    pairs = relevant_str.split(';')
    rel_dict = {}
    for pair in pairs:
        doc_id, grade = pair.split('=')
        rel_dict[doc_id] = int(grade)

    return rel_dict

def compute_metrics(predicted, relevant_dict, k=5) -> tuple[float,float,float,float]:
    hits = sum([1 for doc in predicted[:k] if doc in relevant_dict])
    precision = hits /k     # 정밀도 = 맞춘갯수 / 전체갯수

    # Recall
    total_relevant = len(relevant_dict) # 전체 관련 문서 수
    recall = hits / total_relevant if total_relevant > 0 else 0 # 재현율 = 관련 문서 맞춘 수

    # MRR 예측치 중 첫 관련문서 순위 점수
    rr = 0  # 관련 문서 수
    for idx,doc in enumerate(predicted):
        if doc in relevant_dict:
            rr=1/(idx+1)
            break   # 첫번째 적중 rr반영 후 반복문 탈출

    # AP (MAP를 위한 사전 계산)
    num_correct = 0 # 현재까지의 적중 횟수
    precisions = [] # 적중시의 precision
    for idx, doc in enumerate(predicted[:k]):   # top_k 범위에서
        if doc in relevant_dict:
            num_correct+=1  # 적중시 1 누적
            precisions.append(num_correct/(idx+1))  # 현재 시점의 precision 기록
    ap = np.mean(precisions) if precisions else 0

    return precision, recall, rr, ap

# 여러 쿼리에 대한 평균 성능지표 계산하는 함수
def evaluate_all(method_results,queries_df,k=5):
    prec_list,rec_list,rr_list,ap_list = [],[],[],[]    # 지표별 결과 저장

    for idx, row in queries_df.iterrows():
        qid = row['query_id']   # 쿼리 id
        relevant_dict = parse_relevant(row['relevant_doc_ids'])  # 정답 dict 파싱
        predicted = method_results[qid]     # 해당 쿼리의 예측 랭킹
        p,r,rr,ap = compute_metrics(predicted,relevant_dict,k)  # 지표 계산
        prec_list.append(p)
        rec_list.append(r)
        rr_list.append(rr)
        ap_list.append(ap)

    return{
        'P@k':np.mean(prec_list),
        'R@k':np.mean(rec_list),
        'MRR':np.mean(rr_list),
        'MAP':np.mean(ap_list)
    }

In [25]:
# BM25/Dense 결과로 P@5, R@5, MRR, MAP 계산

bm25_metrics = evaluate_all(bm25_results, queries_df, k=5)
dense_metrics = evaluate_all(dense_results, queries_df, k=5)
hyde_metrics = evaluate_all(hyde_results, queries_df, k=5)

NameError: name 'bm25_results' is not defined

In [26]:
metrics_df = pd.DataFrame({
    'Metrics':['P@5', 'R@5', 'MRR', 'MAP'],
    'BM25' : [bm25_metrics['P@k'],bm25_metrics['R@k'],bm25_metrics['MRR'],bm25_metrics['MAP']],
    'Dense' : [dense_metrics['P@k'],dense_metrics['R@k'],dense_metrics['MRR'],dense_metrics['MAP']],
    'Hyde' : [hyde_metrics['P@k'],hyde_metrics['R@k'],hyde_metrics['MRR'],hyde_metrics['MAP']],
})
metrics_df

NameError: name 'bm25_metrics' is not defined

In [27]:
import matplotlib.pyplot as plt

metrics = ['P@5', 'R@5', 'MRR', 'MAP']
bm25_vals = [bm25_metrics['P@k'], bm25_metrics['R@k'], bm25_metrics['MRR'], bm25_metrics['MAP']]
dense_vals = [dense_metrics['P@k'], dense_metrics['R@k'], dense_metrics['MRR'], dense_metrics['MAP']]
hyde_vals = [hyde_metrics['P@k'], hyde_metrics['R@k'], hyde_metrics['MRR'], hyde_metrics['MAP']]

x = range(len(metrics))  # 0~3

plt.figure(figsize=(8, 4))
plt.plot(x, bm25_vals, marker='o', label='BM25')
plt.plot(x, dense_vals, marker='s', label='Dense')
plt.plot(x, hyde_metrics, marker='s', label='Hyde')
plt.xticks(x, metrics)  # x축 눈금은 0~3 -> 지표명
plt.ylim(0, 1.1)
plt.xlabel('Metrics')
plt.ylabel('Score')
plt.title('BM25 vs Dense vs Hyde Retrival')
plt.legend()
plt.grid()
plt.show()

NameError: name 'bm25_metrics' is not defined

##### HyDE의 역할과 효과
- HyDE는 쿼리를 “의미가 풍부한 가상문서”로 확장
- Dense가 이미 강력한 경우:
    - 성능을 보완하거나 유지
    - 항상 큰 폭의 개선을 보장하지는 않음
- 하지만 쿼리가 짧거나 모호한 경우, HyDE의 효과는 더욱 커질 가능성 있음

- Dense Retrieval은 의미 기반 검색의 기본 선택지
- HyDE는 다음 상황에서 특히 유용:
    - 짧고 추상적인 쿼리
    - 질문형 질의
    - Recall 개선이 중요한 경우
- 실서비스에서는: Dense + (HyDE / BM25 / Rerank) 조합이 가장 현실적인 접근