In [14]:
%pip install nltk scikit-learn pandas numpy matplotlib seaborn

Requirement already satisfied: nltk in .\nlp_venv\Lib\site-packages (3.10.2)
Requirement already satisfied: scikit-learn in .\nlp_venv\Lib\site-packages (1.9.0)
Requirement already satisfied: pandas in .\nlp_venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in .\nlp_venv\Lib\site-packages (2.5.1)
Requirement already satisfied: matplotlib in .\nlp_venv\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in .\nlp_venv\Lib\site-packages (0.13.2)
Requirement already satisfied: defusedxml in .\nlp_venv\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in .\nlp_venv\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in .\nlp_venv\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in .\nlp_venv\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in .\nlp_venv\Lib\site-packages (from nltk) (4.70.0)
Requirement already satisfied: scipy>=1.10.0 in .\nlp_venv\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: narwhals>=2.0.1 in .\nlp_venv\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\nlp_venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\nlp_venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\nlp_venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in .\nlp_venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\nlp_venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\nlp_venv\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\nlp_venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\nlp_venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in .\nlp_venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\nlp_venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\nlp_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in .\nlp_venv\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import nltk

nltk.download('punkt')  # 토크나이저를 위한 데이터 다운로드
nltk.download('stopwords')  # 불용어를 위한 데이터 다운로드
nltk.download('wordnet')  # WordNet을 위한 데이터 다운로드

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [16]:
import nltk
print(nltk.data.path)

['C:\\Users\\uk/nltk_data', 'c:\\Users\\UK\\SKN\\nlp_analysis\\nlp_venv\\nltk_data', 'c:\\Users\\UK\\SKN\\nlp_analysis\\nlp_venv\\share\\nltk_data', 'c:\\Users\\UK\\SKN\\nlp_analysis\\nlp_venv\\lib\\nltk_data', 'C:\\Users\\uk\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']

In [17]:
import os
for p in nltk.data.path:
    punkt_path = os.path.join(p, 'tokenizers', 'punkt')
    punkt_tab_path = os.path.join(p, 'tokenizers', 'punkt_tab')
    print(p)
    print('  punkt exists:', os.path.exists(punkt_path))
    print('  punkt_tab exists:', os.path.exists(punkt_tab_path))

C:\Users\uk/nltk_data
  punkt exists: False
  punkt_tab exists: False
c:\Users\UK\SKN\nlp_analysis\nlp_venv\nltk_data
  punkt exists: False
  punkt_tab exists: False
c:\Users\UK\SKN\nlp_analysis\nlp_venv\share\nltk_data
  punkt exists: False
  punkt_tab exists: False
c:\Users\UK\SKN\nlp_analysis\nlp_venv\lib\nltk_data
  punkt exists: False
  punkt_tab exists: False
C:\Users\uk\AppData\Roaming\nltk_data
  punkt exists: True
  punkt_tab exists: True
C:\nltk_data
  punkt exists: False
  punkt_tab exists: False
D:\nltk_data
  punkt exists: False
  punkt_tab exists: False
E:\nltk_data
  punkt exists: False
  punkt_tab exists: False

In [18]:
from nltk.tokenize import word_tokenize
text = "NLTK is a powerful library for NLP!!!!!"
print(word_tokenize(text))

['NLTK', 'is', 'a', 'powerful', 'library', 'for', 'NLP', '!', '!', '!', '!', '!']

In [19]:
import nltk
result = nltk.download('punkt_tab')
print('download result:', result)

download result: True

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [20]:
import os
path = 'C:\\Users\\uk\\AppData\\Roaming\\nltk_data'
print(os.path.exists(os.path.join(path, 'tokenizers', 'punkt_tab')))

True

In [21]:
from nltk.tokenize import word_tokenize, sent_tokenize # 단어/문장 토큰화 도구

text = "NLTK is a powerful library for NLP!!!!!"
word_tokenize(text) # 단어 토큰화

['NLTK',
 'is',
 'a',
 'powerful',
 'library',
 'for',
 'NLP',
 '!',
 '!',
 '!',
 '!',
 '!']

In [22]:
text = "NLTK is a powerful library for NLP! NLTK is a powerful library for NLP. NLTK is a powerful library for NLP?"
sent_tokenize(text) # 문장 토큰화

['NLTK is a powerful library for NLP!',
 'NLTK is a powerful library for NLP.',
 'NLTK is a powerful library for NLP?']

In [23]:
def tokenize_text(text):
    sentences = sent_tokenize(text) # 문장토큰화
    return [word_tokenize(sentence) for sentence  in sentences]

tokenize_text(text)

[['NLTK', 'is', 'a', 'powerful', 'library', 'for', 'NLP', '!'],
 ['NLTK', 'is', 'a', 'powerful', 'library', 'for', 'NLP', '.'],
 ['NLTK', 'is', 'a', 'powerful', 'library', 'for', 'NLP', '?']]

In [24]:
# NLTK N-gram(바이그램/트라이그램) 생성
from nltk import ngrams

text = "The Martrix is everywhere its all arounds us, here even in this room"

tokens = word_tokenize(text)   # 단어 토큰화
print(tokens)

bigram = ngrams(tokens, 2)      #2-gram(바이그램) 생성
print([token for token in bigram])

trigram = ngrams(tokens, 3)     #3-gram(트라이그램) 생성
print([token for token in trigram])

['The', 'Martrix', 'is', 'everywhere', 'its', 'all', 'arounds', 'us', ',', 'here', 'even', 'in', 'this', 'room']
[('The', 'Martrix'), ('Martrix', 'is'), ('is', 'everywhere'), ('everywhere', 'its'), ('its', 'all'), ('all', 'arounds'), ('arounds', 'us'), ('us', ','), (',', 'here'), ('here', 'even'), ('even', 'in'), ('in', 'this'), ('this', 'room')]
[('The', 'Martrix', 'is'), ('Martrix', 'is', 'everywhere'), ('is', 'everywhere', 'its'), ('everywhere', 'its', 'all'), ('its', 'all', 'arounds'), ('all', 'arounds', 'us'), ('arounds', 'us', ','), ('us', ',', 'here'), (',', 'here', 'even'), ('here', 'even', 'in'), ('even', 'in', 'this'), ('in', 'this', 'room')]

In [25]:
# 불용어 코퍼스
from nltk.corpus import stopwords

print(stopwords.fileids()) # 지원되는 언어 확인(한국어 지원안함)

['albanian', 'arabic', 'azerbaijani', 'basque', 'belarusian', 'bengali', 'catalan', 'chinese', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hebrew', 'hinglish', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'tamil', 'turkish', 'uzbek']

In [26]:
print(stopwords.words('english'))
print(len(stopwords.words('english')))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
198

In [27]:
text = "The Martrix is everywhere its all arounds us, here even in this room"
stopwords_list = stopwords.words('english') # 영어 불용어 리스트

tokens =[]
for word in word_tokenize(text):    # 단어 토큰화
    word = word.lower()             # 소문자 변환
    if word not in stopwords_list:  # 불용어 제외
        tokens.append(word)

tokens

['martrix', 'everywhere', 'arounds', 'us', ',', 'even', 'room']

### 특성 벡터화
- BOW > CounVectorizer

In [28]:
text1 = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.'

text2 = 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe \
You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'

texts = [text1, text2]
texts

['The Matrix is everywhere its all around us, here even in this room. You can see it out your window or on your television. You feel it when you go to work, or go to church or pay your taxes.',
 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.']

In [29]:
# countVEctorizer로 BOW 벡터화
from sklearn.feature_extraction.text import CountVectorizer # BOW(단어 빈도) 벡터화 도구

count_vectorizer = CountVectorizer() # CountVectorizer 객체 생성
count_vectorizer.fit(texts) # 단어 사전 학습 (vocabulary 생성)
text_vecs = count_vectorizer.transform(texts) # 단어를 BOW 벡터화 변환 (희소행렬 생성)

print(text_vecs)

print(type(text_vecs), type(text_vecs.toarray()))   # <class 'scipy.sparse._csr.csr_matrix'>
text_vecs.toarray() # 희소행렬을 배열 형태로 변환

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 56 stored elements and shape (2, 51)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 7)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	2
  (0, 15)	1
  (0, 18)	1
  (0, 19)	1
  (0, 20)	2
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	3
  (0, 25)	1
  (0, 26)	1
  (0, 30)	1
  (0, 31)	1
  (0, 36)	1
  (0, 37)	1
  (0, 38)	1
  (0, 39)	1
  (0, 40)	2
  :	:
  (1, 1)	4
  (1, 3)	1
  (1, 4)	2
  (1, 5)	1
  (1, 8)	1
  (1, 9)	1
  (1, 14)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	2
  (1, 27)	2
  (1, 28)	1
  (1, 29)	1
  (1, 32)	1
  (1, 33)	1
  (1, 34)	1
  (1, 35)	2
  (1, 38)	4
  (1, 40)	1
  (1, 42)	1
  (1, 43)	1
  (1, 44)	1
  (1, 47)	1
  (1, 49)	7
  (1, 50)	1
<class 'scipy.sparse._csr.csr_matrix'> <class 'numpy.ndarray'>

array([[1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 2, 1,
        1, 1, 3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0,
        0, 1, 1, 0, 1, 3, 3],
       [0, 4, 0, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0, 4, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 7, 1]])

In [30]:
print(count_vectorizer.get_feature_names_out())  # 단어 사전 (특성 이름 목록)
print(count_vectorizer.vocabulary_) # 단어 사전 확인

['all' 'and' 'around' 'bed' 'believe' 'blue' 'can' 'church' 'deep' 'ends'
 'even' 'everywhere' 'feel' 'go' 'goes' 'here' 'hole' 'how' 'in' 'is' 'it'
 'its' 'matrix' 'on' 'or' 'out' 'pay' 'pill' 'rabbit' 'red' 'room' 'see'
 'show' 'stay' 'story' 'take' 'taxes' 'television' 'the' 'this' 'to' 'us'
 'wake' 'want' 'whatever' 'when' 'window' 'wonderland' 'work' 'you' 'your']
{'the': 38, 'matrix': 22, 'is': 19, 'everywhere': 11, 'its': 21, 'all': 0, 'around': 2, 'us': 41, 'here': 15, 'even': 10, 'in': 18, 'this': 39, 'room': 30, 'you': 49, 'can': 6, 'see': 31, 'it': 20, 'out': 25, 'your': 50, 'window': 46, 'or': 24, 'on': 23, 'television': 37, 'feel': 12, 'when': 45, 'go': 13, 'to': 40, 'work': 48, 'church': 7, 'pay': 26, 'taxes': 36, 'take': 35, 'blue': 5, 'pill': 27, 'and': 1, 'story': 34, 'ends': 9, 'wake': 42, 'bed': 3, 'believe': 4, 'whatever': 44, 'want': 43, 'red': 29, 'stay': 33, 'wonderland': 47, 'show': 32, 'how': 17, 'deep': 8, 'rabbit': 28, 'hole': 16, 'goes': 14}

In [31]:
import pandas as pd

vacab = sorted(count_vectorizer.vocabulary_.items(), key=lambda x:x[1]) # 인덱스 기준 오름차순 정렬
vocab_df = pd.DataFrame(vacab, columns=['word', 'idx']) # (단어,인덱스) 데이터프레임 생성
vocab_df

          word  idx
0          all    0
1          and    1
2       around    2
3          bed    3
4      believe    4
5         blue    5
6          can    6
7       church    7
8         deep    8
9         ends    9
10        even   10
11  everywhere   11
12        feel   12
13          go   13
14        goes   14
15        here   15
16        hole   16
17         how   17
18          in   18
19          is   19
20          it   20
21         its   21
22      matrix   22
23          on   23
24          or   24
25         out   25
26         pay   26
27        pill   27
28      rabbit   28
29         red   29
30        room   30
31         see   31
32        show   32
33        stay   33
34       story   34
35        take   35
36       taxes   36
37  television   37
38         the   38
39        this   39
40          to   40
41          us   41
42        wake   42
43        want   43
44    whatever   44
45        when   45
46      window   46
47  wonderland   47
48        work   48
49         you   49
50        your   50

In [32]:
# 단어 빈도수 계산하여 DataFrame에 추가
word_counts = text_vecs.toarray().sum(axis=0) # 전체 문서 기준 단어별 합계

print(word_counts)

vocab_df['count'] = vocab_df['idx'].apply(lambda i: word_counts[i]) # 빈도값 컬럼 추가

vocab_df = vocab_df.drop(columns=['idx']) 

vocab_df

[ 1  4  1  1  2  1  1  1  1  1  1  1  1  2  1  1  1  1  3  1  2  1  1  1
  3  1  1  2  1  1  1  1  1  1  1  2  1  1  5  1  3  1  1  1  1  1  1  1
  1 10  4]

          word  count
0          all      1
1          and      4
2       around      1
3          bed      1
4      believe      2
5         blue      1
6          can      1
7       church      1
8         deep      1
9         ends      1
10        even      1
11  everywhere      1
12        feel      1
13          go      2
14        goes      1
15        here      1
16        hole      1
17         how      1
18          in      3
19          is      1
20          it      2
21         its      1
22      matrix      1
23          on      1
24          or      3
25         out      1
26         pay      1
27        pill      2
28      rabbit      1
29         red      1
30        room      1
31         see      1
32        show      1
33        stay      1
34       story      1
35        take      2
36       taxes      1
37  television      1
38         the      5
39        this      1
40          to      3
41          us      1
42        wake      1
43        want      1
44    whatever      1
45        when      1
46      window      1
47  wonderland      1
48        work      1
49         you     10
50        your      4

In [33]:
# Countvectorizer 불용어 제거 및 벡터화
count_vectorizer = CountVectorizer(stop_words='english') # 영어 불용어 제거 CountVectorizer 객체 생성
texts_vecs = count_vectorizer.fit_transform(texts) # 단어 사전 학습(생성) 및 벡터화 적용
print(texts_vecs.toarray().shape)

vacab = sorted(count_vectorizer.vocabulary_.items(), key=lambda x:x[1]) # 인덱스 기준 오름차순 정렬
vocab_df = pd.DataFrame(vacab, columns=['word', 'idx']) # (단어,인덱스) 데이터프레임 생성
vocab_df

(2, 24)

          word  idx
0          bed    0
1      believe    1
2         blue    2
3       church    3
4         deep    4
5         ends    5
6         feel    6
7         goes    7
8         hole    8
9       matrix    9
10         pay   10
11        pill   11
12      rabbit   12
13         red   13
14        room   14
15        stay   15
16       story   16
17       taxes   17
18  television   18
19        wake   19
20        want   20
21      window   21
22  wonderland   22
23        work   23

In [34]:
count_vectorizer = CountVectorizer(
    stop_words='english', # 영어 불용어 적용
    ngram_range=(1, 2),   # 1-gram(단어)과 2-gram(바이그램) 모두 추출
    max_features=20       # 빈도수 기준 상위 20개 특성만 사용
)

texts_vecs = count_vectorizer.fit_transform(texts) # 학습 및 BOW변환(희소행렬)
print(texts_vecs.toarray().shape) # (문서수,특성수)

count_vectorizer.get_feature_names_out() # 단어 사전 확인(선택된 단어/바이어그램)

(2, 20)

array(['bed', 'bed believe', 'believe', 'believe red', 'believe want',
       'blue', 'blue pill', 'church', 'church pay', 'deep', 'deep rabbit',
       'ends', 'ends wake', 'feel', 'feel work', 'goes', 'hole',
       'hole goes', 'matrix', 'pill'], dtype=object)

- BOW > TfIdfVectorizer
    - TF-IDF == Term Frequency-Inverse Document Frequency

**TfidfVectorizer의 주요 파라미터**
<table border="1" cellpadding="5" cellspacing="0">
  <tr style="background-color: #f2f2f2;">
    <th>Parameter</th>
    <th>Description</th>
    <th>Default Value</th>
  </tr>
  <tr style="background-color: #ffeb99;">
    <td><b>max_df</b></td>
    <td>문서의 비율 값으로서, 해당 비율 이상 나타나는 단어를 무시한다. <br> 예를 들어, max_df=0.8이면, 80% 이상의 문서에서 나타나는 단어는 제외된다.</td>
    <td>1.0</td>
  </tr>
  <tr style="background-color: #ffeb99;">
    <td><b>min_df</b></td>
    <td>문서의 비율 값 또는 정수로, 해당 비율 이하 나타나는 단어를 무시한다. <br> 예를 들어, min_df=2이면, 두 개 이하의 문서에서만 나타나는 단어는 제외된다.</td>
    <td>1</td>
  </tr>
  <tr style="background-color: #ffeb99;">
    <td><b>ngram_range</b></td>
    <td>(min_n, max_n) 형식으로, 사용할 n-gram의 범위를 정의한다. <br> 예를 들어, (1, 2)로 설정하면 unigram과 bigram을 고려한다.</td>
    <td>(1, 1)</td>
  </tr>
  <tr style="background-color: #ffeb99;">
    <td>stop_words</td>
    <td>불용어를 지정할 수 있다. "english"로 설정하면 영어 불용어를 사용한다.</td>
    <td>None</td>
  </tr>
  <tr>
    <td>max_features</td>
    <td>벡터화할 때 고려할 최대 단어 수를 설정한다. 빈도순으로 상위 단어들이 선택된다.</td>
    <td>None</td>
  </tr>
  <tr>
    <td>use_idf</td>
    <td>IDF(역문서 빈도)를 사용할지 여부를 지정한다. False로 설정하면 단순히 TF 값만 사용한다.</td>
    <td>True</td>
  </tr>
  <tr>
    <td>smooth_idf</td>
    <td>IDF 계산 시, 0으로 나누는 것을 피하기 위해 추가적인 smoothing을 수행한다.</td>
    <td>True</td>
  </tr>
  <tr>
    <td>sublinear_tf</td>
    <td>TF 값에 대해 sublinear scaling (1 + log(tf))를 적용할지 지정한다.</td>
    <td>False</td>
  </tr>

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer # TF-IDF 벡터화 도구

tfidf_vectorizer = TfidfVectorizer(stop_words='english') # 영어 불용어 제거 TF-IDF 벡터화 객체 생성
texts_vecs = tfidf_vectorizer.fit_transform(texts) # 학습 및 TF-IDF 변환(희소행렬)

print(text_vecs)
print(texts_vecs.toarray())
print(tfidf_vectorizer.get_feature_names_out()) # 단어 사전 확인
tfidf_vectorizer.vocabulary_ # 단어-인덱스 매핑사전

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 56 stored elements and shape (2, 51)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 7)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	2
  (0, 15)	1
  (0, 18)	1
  (0, 19)	1
  (0, 20)	2
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	3
  (0, 25)	1
  (0, 26)	1
  (0, 30)	1
  (0, 31)	1
  (0, 36)	1
  (0, 37)	1
  (0, 38)	1
  (0, 39)	1
  (0, 40)	2
  :	:
  (1, 1)	4
  (1, 3)	1
  (1, 4)	2
  (1, 5)	1
  (1, 8)	1
  (1, 9)	1
  (1, 14)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	2
  (1, 27)	2
  (1, 28)	1
  (1, 29)	1
  (1, 32)	1
  (1, 33)	1
  (1, 34)	1
  (1, 35)	2
  (1, 38)	4
  (1, 40)	1
  (1, 42)	1
  (1, 43)	1
  (1, 44)	1
  (1, 47)	1
  (1, 49)	7
  (1, 50)	1
[[0.         0.         0.         0.33333333 0.         0.
  0.33333333 0.         0.         0.33333333 0.33333333 0.
  0.         0.         0.33333333 0.         0.         0.33333333
  0.33333333 0.         0.         0.33333333 0.         0.33333333]
 [0.21821789 0.43643578 0.21821789 0.         0.21821789 0.21821789
  0.         0.21821789 0.21821789 0.         0.         0.43643578
  0.21821789 0.21821789 0.         0.21821789 0.21821789 0.
  0.         0.21821789 0.21821789 0.         0.21821789 0.        ]]
['bed' 'believe' 'blue' 'church' 'deep' 'ends' 'feel' 'goes' 'hole'
 'matrix' 'pay' 'pill' 'rabbit' 'red' 'room' 'stay' 'story' 'taxes'
 'television' 'wake' 'want' 'window' 'wonderland' 'work']

{'matrix': 9,
 'room': 14,
 'window': 21,
 'television': 18,
 'feel': 6,
 'work': 23,
 'church': 3,
 'pay': 10,
 'taxes': 17,
 'blue': 2,
 'pill': 11,
 'story': 16,
 'ends': 5,
 'wake': 19,
 'bed': 0,
 'believe': 1,
 'want': 20,
 'red': 13,
 'stay': 15,
 'wonderland': 22,
 'deep': 4,
 'rabbit': 12,
 'hole': 8,
 'goes': 7}